/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Rectangle;
import java.awt.geom.Rectangle2D;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Administrador
 */
public class juego extends javax.swing.JFrame {

    int x; //en x y guardamos la posicion
    int y;
    

    /**
     * Creates new form juego
     */
    public juego() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jPanel1.setFocusable(true); //aca iniciamos el jPanel
        jPanel1.setBackground(Color.ORANGE);
        
                 

    }

  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hotairballoon3x_99139 (1).png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rectangulo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        //hacemos el evento KeyPressed con boton derecho en el frame, para cuando apretamos el teclado
        x = jLabel1.getX();
        y = jLabel1.getY();
        ;

        System.out.println(jLabel1.getLocation());

        switch (evt.getExtendedKeyCode()) { //aca capturamos las teclas

          
            
            case KeyEvent.VK_UP:
                if (jLabel1.getY() >= -7) {
                    jLabel1.setLocation(x, y - 5); //tecla de arriba, limite y -7
                }

                break;

            case KeyEvent.VK_DOWN:
                if (jLabel1.getY() <= 338) {
                    jLabel1.setLocation(x, y + 5);//tecla de abajo, limite y 338
                }

                break;

            case KeyEvent.VK_RIGHT:
               

                if (jLabel1.getX() <= 470) {

                    jLabel1.setLocation(x + 5, y);// tecla derecha, limite x 470 
                    
                }
                if (colision(jLabel2.getBounds())) {
                   
                    System.out.println("colision");
                    //jLabel1.setLocation(x+5, y);// tecla derecha, limite x 470 
                   
                    
                    
                }
                if (x==318) {
                     jLabel1.setLocation(x+5, y);// tecla derecha, limite x 470 

                    
                    
                }
            

                break;

            case KeyEvent.VK_LEFT:
                if (jLabel1.getX() >= -20) {
                    jLabel1.setLocation(x - 5, y);//tecla de izquierda, limite x -20

                }

                break;

        }


    }//GEN-LAST:event_jPanel1KeyPressed

    public JPanel getjPanel1() {
        return jPanel1;
    }

    private boolean colision(Rectangle2D r) {
       
      x=318;
   
       
        return jLabel1.getBounds().intersects(r);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
