/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.List;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import jugadores.util.HibernateUtil;
import modelo.Jugador;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import presentador.Presentador;

/**
 *
 * @author pablo
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private Presentador presentador;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.presentador = new Presentador(this);
        setLocationRelativeTo(this);
    }

    // 1 definis la consulta pero no esta completa
    private static String primeraConsulta = "from Jugador a Where a.nombre like '";

    //3 completa lo que inicie en el paso 1, por ejemplo si pongo fede me va a traer federico o federica, es para que funciones el like
    private void completarElNombre() {
        executeHQLQuery(primeraConsulta + getjTextField1Nombre_buscar().getText()+"%'");

    }

    private void executeHQLQuery(String hql) {
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q = session.createQuery(hql);
            List resultList = q.list();
            displayResult(resultList);
            session.getTransaction().commit();
        } catch (HibernateException he) {
            he.printStackTrace();
        }
    }

    private void displayResult(List resultList) {
    Vector<String> tableColumnas = new Vector<String>();
    Vector tableData = new Vector();
    tableColumnas.add("ID"); 
    tableColumnas.add("NOMBRE");
    tableColumnas.add("DIA NACIMIENTO");
    tableColumnas.add("MES NACIMIENTO");
    tableColumnas.add("AÑO NACIMIENTO");

    for(Object o : resultList) {
        Jugador jugador = (Jugador)o;
        Vector<Object> oneRow = new Vector<Object>();
        oneRow.add(jugador.getIdjugador());
        oneRow.add(jugador.getNombre());
        oneRow.add(jugador.getDiaNacimiento());
        oneRow.add(jugador.getMesNacimiento());
        oneRow.add(jugador.getAñoNacimiento());
        tableData.add(oneRow);
    }
    getjTable1TablaParaBuscar().setModel(new DefaultTableModel(tableData, tableColumnas));
}

    public JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    public JComboBox<Object> getjComboBoxAño() {
        return jComboBoxAño;
    }

    public JComboBox<Object> getjComboBoxDia() {
        return jComboBoxDia;
    }

    public JComboBox<Object> getjComboBoxMes() {
        return jComboBoxMes;
    }

    public JTable getjTable1TablaParaBuscar() {
        return jTable1TablaParaBuscar;
    }

    public JTextField getjTextField1Nombre_buscar() {
        return jTextField1Nombre_buscar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jComboBoxAño = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonMostrarReporte = new javax.swing.JButton();
        jButtonGuardarJugador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1TablaParaBuscar = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1Nombre_buscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1Buscar_Nombre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 14, 215, 30));

        jLabel1.setText("NOMBRE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 27, 95, -1));

        getContentPane().add(jComboBoxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 67, 54, -1));

        getContentPane().add(jComboBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 67, 83, -1));

        getContentPane().add(jComboBoxAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 67, 70, -1));

        jLabel2.setText("/");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 70, -1, -1));

        jLabel3.setText("/");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 70, 12, -1));

        jLabel4.setText("FECHA DE NACIMIENTO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 70, 148, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jButtonMostrarReporte.setText("Mostrar Planilla");
        jButtonMostrarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarReporteActionPerformed(evt);
            }
        });

        jButtonGuardarJugador.setText("Guardar");
        jButtonGuardarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarJugadorActionPerformed(evt);
            }
        });

        jTable1TablaParaBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DIA NACIMIENTO", "MES NACIMIENTO", "AÑO NACIMIENTO"
            }
        ));
        jScrollPane1.setViewportView(jTable1TablaParaBuscar);

        jLabel5.setText("NOMBRE:");

        jButton1Buscar_Nombre.setText("Buscar");
        jButton1Buscar_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1Buscar_NombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonMostrarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1Nombre_buscar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1Buscar_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonGuardarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMostrarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField1Nombre_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1Buscar_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarJugadorActionPerformed
        this.presentador.guardarJugadorApretado();
    }//GEN-LAST:event_jButtonGuardarJugadorActionPerformed

    private void jButtonMostrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarReporteActionPerformed
        this.presentador.mostrarReporteApretado();
    }//GEN-LAST:event_jButtonMostrarReporteActionPerformed

    private void jButton1Buscar_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1Buscar_NombreActionPerformed
        //2, significa no vacio
        if (!getjTextField1Nombre_buscar().getText().trim().equals(""))
            completarElNombre();
           
    }//GEN-LAST:event_jButton1Buscar_NombreActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Buscar_Nombre;
    private javax.swing.JButton jButtonGuardarJugador;
    private javax.swing.JButton jButtonMostrarReporte;
    private javax.swing.JComboBox<Object> jComboBoxAño;
    private javax.swing.JComboBox<Object> jComboBoxDia;
    private javax.swing.JComboBox<Object> jComboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1TablaParaBuscar;
    private javax.swing.JTextField jTextField1Nombre_buscar;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}


