/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.List;
import java.util.Vector;
import javax.management.Query;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Empleado;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import presentador.Presentador;
import pruebacalculadorasueldo.util.HibernateUtil;

/**
 *
 * @author pablo
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private Presentador presentador;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.presentador = new Presentador(this);
        setLocationRelativeTo(this);
    }

    public JTextField getjTextField1nombre_empleado() {
        return jTextField1nombre_empleado;
    }

    public JTextField getjTextField2apellido_empleado() {
        return jTextField2apellido_empleado;
    }

    public JTextField getjTextField3DNI_empleado() {
        return jTextField3DNI_empleado;
    }

    public JTextField getjTextField4SueldoBase_empleado() {
        return jTextField4SueldoBase_empleado;
    }

    public JTextField getjTextField1PrecioDelArticulo() {
        return jTextField1PrecioDelArticulo;
    }

    public JTextField getjTextField2cantidadDeArticulosVendidos() {
        return jTextField2cantidadDeArticulosVendidos;
    }

    public JComboBox<Object> getjComboBox1Empleados() {
        return jComboBox1Empleados;
    }

    public JTextField getjTextField3IDEmpleado() {
        return jTextField3IDEmpleado;
    }

    public JTextField getjTextField1Nombre_buscador() {
        return jTextField1Nombre_buscador;
    }

    public JTextField getjTextField2apellido_buscador() {
        return jTextField2apellido_buscador;
    }

    public JTable getjTable1Empleado() {
        return jTable1Empleado;
    }
    //1 defino la consulta pero no esta completa
    private static String consultaBasadaEnElNombre = "from Empleado a where a.nombre like '";
    private static String consultaBasadaEnapellido = "from Empleado a where a.apellido like '";

    private void ejecutarHQLQuery(String hql) {
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            org.hibernate.Query q = session.createQuery(hql);
            List resultList = q.list();
            displayResult(resultList);
            session.getTransaction().commit();
        } catch (HibernateException he) {
            he.printStackTrace();
        }

    }

    private void displayResult(List resultList) {
        Vector tableDate = new Vector();
        Vector<String> tableHeaders = new Vector<>();
        tableHeaders.add("id");
        tableHeaders.add("nombre");
        tableHeaders.add("apellido");
        tableHeaders.add("dni");
        tableHeaders.add("sueldo base");

        for (Object o : resultList) {
            Empleado empleado = (Empleado) o;
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(empleado.getIdempleado());
            oneRow.add(empleado.getNombre());
            oneRow.add(empleado.getApellido());
            oneRow.add(empleado.getDni());
            oneRow.add(empleado.getSueldoBase());
            tableDate.add(oneRow);
            jTable1Empleado.setModel(new DefaultTableModel(tableDate, tableHeaders));

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField1nombre_empleado = new javax.swing.JTextField();
        jTextField2apellido_empleado = new javax.swing.JTextField();
        jTextField3DNI_empleado = new javax.swing.JTextField();
        jTextField4SueldoBase_empleado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1guardarDatosPersonales = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Empleado = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1Nombre_buscador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2apellido_buscador = new javax.swing.JTextField();
        jButton1Buscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1PrecioDelArticulo = new javax.swing.JTextField();
        jTextField2cantidadDeArticulosVendidos = new javax.swing.JTextField();
        jTextField3IDEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1GuardarArticulo = new javax.swing.JButton();
        jButton1CalcularSueldo = new javax.swing.JButton();
        jComboBox1Empleados = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);
        jPanel2.add(jTextField1nombre_empleado);
        jTextField1nombre_empleado.setBounds(190, 20, 195, 31);
        jPanel2.add(jTextField2apellido_empleado);
        jTextField2apellido_empleado.setBounds(190, 60, 195, 33);
        jPanel2.add(jTextField3DNI_empleado);
        jTextField3DNI_empleado.setBounds(190, 110, 195, 31);
        jPanel2.add(jTextField4SueldoBase_empleado);
        jTextField4SueldoBase_empleado.setBounds(190, 150, 195, 29);

        jLabel1.setText("NOMBRE:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 30, 70, 14);

        jLabel2.setText("APELLIDO:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 70, 80, 14);

        jLabel3.setText("DNI:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 120, 50, 14);

        jLabel4.setText("SUELDO BASE:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(80, 160, 94, 14);

        jButton1guardarDatosPersonales.setText("guardar datos personales");
        jButton1guardarDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1guardarDatosPersonalesActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1guardarDatosPersonales);
        jButton1guardarDatosPersonales.setBounds(440, 90, 215, 31);

        jTable1Empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1Empleado);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(22, 312, 690, 190);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(10, 210, 720, 10);
        jPanel2.add(jTextField1Nombre_buscador);
        jTextField1Nombre_buscador.setBounds(100, 230, 110, 30);

        jLabel9.setText("NOMBRE:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 240, 70, 14);

        jLabel10.setText("APELLIDO:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(280, 240, 70, 14);
        jPanel2.add(jTextField2apellido_buscador);
        jTextField2apellido_buscador.setBounds(350, 230, 150, 30);

        jButton1Buscar.setText("Buscar");
        jButton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BuscarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1Buscar);
        jButton1Buscar.setBounds(540, 230, 170, 40);

        jTabbedPane1.addTab("Empleado", jPanel2);

        jLabel5.setText("CANTIDAD DE ARTICULOS VENDIDOS:");

        jLabel6.setText("PRECIO DEL ARTICULO:");

        jLabel7.setText("ID EMPLEADO:");

        jButton1GuardarArticulo.setText("guardar Articulo");
        jButton1GuardarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GuardarArticuloActionPerformed(evt);
            }
        });

        jButton1CalcularSueldo.setText("Calcular Sueldo");
        jButton1CalcularSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CalcularSueldoActionPerformed(evt);
            }
        });

        jLabel8.setText("EMPLEADOS:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(jButton1CalcularSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1PrecioDelArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3IDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2cantidadDeArticulosVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1GuardarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2cantidadDeArticulosVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1PrecioDelArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3IDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addComponent(jButton1GuardarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1CalcularSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Articulo", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1guardarDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1guardarDatosPersonalesActionPerformed
        this.presentador.guardarEmpleadoApretado();
    }//GEN-LAST:event_jButton1guardarDatosPersonalesActionPerformed

    private void jButton1GuardarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GuardarArticuloActionPerformed
        this.presentador.guardarArticuloApretado();
    }//GEN-LAST:event_jButton1GuardarArticuloActionPerformed

    private void jButton1CalcularSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CalcularSueldoActionPerformed
        this.presentador.calcularSueldoApretado();
    }//GEN-LAST:event_jButton1CalcularSueldoActionPerformed

    private void jButton1BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarActionPerformed
        if (!jTextField1Nombre_buscador.getText().trim().equals("")) {
            ejecutarHQLQuery_Nombre();
        } else if (!jTextField2apellido_buscador.getText().trim().equals("")) {
            ejecutarHQLQuery_apellido();
        }


    }//GEN-LAST:event_jButton1BuscarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Buscar;
    private javax.swing.JButton jButton1CalcularSueldo;
    private javax.swing.JButton jButton1GuardarArticulo;
    private javax.swing.JButton jButton1guardarDatosPersonales;
    private javax.swing.JComboBox<Object> jComboBox1Empleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1Empleado;
    private javax.swing.JTextField jTextField1Nombre_buscador;
    private javax.swing.JTextField jTextField1PrecioDelArticulo;
    private javax.swing.JTextField jTextField1nombre_empleado;
    private javax.swing.JTextField jTextField2apellido_buscador;
    private javax.swing.JTextField jTextField2apellido_empleado;
    private javax.swing.JTextField jTextField2cantidadDeArticulosVendidos;
    private javax.swing.JTextField jTextField3DNI_empleado;
    private javax.swing.JTextField jTextField3IDEmpleado;
    private javax.swing.JTextField jTextField4SueldoBase_empleado;
    // End of variables declaration//GEN-END:variables

    private void ejecutarHQLQuery_Nombre() {
        ejecutarHQLQuery(consultaBasadaEnElNombre +jTextField1Nombre_buscador.getText()+"%'" );
    }

    // 3 Esta funcion toma lo que definiste en el paso 1, y la completa, en este caso toma el NOMBRE y le agrega el simbolo % (es para que funcionae el like)
    // Por ejemplo, ingreso fede, me va a buscar todos los nombres que empiecen con fede por ejemplo: federico, federica. 
    // La consulta completa quedaria "from Actor a where a.firstName like 'fede%'"
    private void ejecutarHQLQuery_apellido() {
        ejecutarHQLQuery(consultaBasadaEnapellido +jTextField2apellido_buscador.getText()+"%'" );
    }
}
