package modelo;
// Generated 03/04/2019 22:06:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idpersona;
     private String nombre;
     private String apellido;
     private int edad;
     private Date fecha;
     private Set viajeses = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String nombre, String apellido, int edad, Date fecha) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.edad = edad;
        this.fecha = fecha;
    }
    public Persona(String nombre, String apellido, int edad, Date fecha, Set viajeses) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
       this.fecha = fecha;
       this.viajeses = viajeses;
    }
   
    public Integer getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(Integer idpersona) {
        this.idpersona = idpersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getViajeses() {
        return this.viajeses;
    }
    
    public void setViajeses(Set viajeses) {
        this.viajeses = viajeses;
    }

    @Override
    public String toString() {
        return  idpersona + " "+ nombre + " " + apellido;
    }
    
    
    

  
    
    
    




}


