package modelo;
// Generated 03/04/2019 22:06:51 by Hibernate Tools 4.3.1



/**
 * Viajes generated by hbm2java
 */
public class Viajes  implements java.io.Serializable {


     private Integer idviajes;
     private Persona persona;
     private String ciudad;
     private String pais;
     private String fechaDelViaje;

    public Viajes() {
    }

    public Viajes(Persona persona, String ciudad, String pais, String fechaDelViaje) {
       this.persona = persona;
       this.ciudad = ciudad;
       this.pais = pais;
       this.fechaDelViaje = fechaDelViaje;
    }
   
    public Integer getIdviajes() {
        return this.idviajes;
    }
    
    public void setIdviajes(Integer idviajes) {
        this.idviajes = idviajes;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getFechaDelViaje() {
        return this.fechaDelViaje;
    }
    
    public void setFechaDelViaje(String fechaDelViaje) {
        this.fechaDelViaje = fechaDelViaje;
    }




}


