package modelo;
// Generated 19/02/2019 14:59:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private Integer idvendedor;
     private String nombre;
     private Date horaFecha;

    public Vendedor() {
    }

    public Vendedor(String nombre, Date horaFecha) {
       this.nombre = nombre;
       this.horaFecha = horaFecha;
    }
   
    public Integer getIdvendedor() {
        return this.idvendedor;
    }
    
    public void setIdvendedor(Integer idvendedor) {
        this.idvendedor = idvendedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getHoraFecha() {
        return this.horaFecha;
    }
    
    public void setHoraFecha(Date horaFecha) {
        this.horaFecha = horaFecha;
    }

    @Override
    public String toString() {
        return idvendedor + ", nombre=" + nombre + ", horaFecha=" + horaFecha;
    }
    
    
    




}


