package modelo;
// Generated 30/01/2020 17:37:59 by Hibernate Tools 4.3.1



/**
 * Comprobante generated by hbm2java
 */
public class Comprobante  implements java.io.Serializable {


     private Integer idComprobante;
     private Fabrica fabrica;
     private Repuesto repuesto;
     private double precioDelRepuesto;
     private int cantidadDeRepuestos;
     private double total;
     private double totalApagar;

    public Comprobante() {
    }

    public Comprobante(Fabrica fabrica, Repuesto repuesto, double precioDelRepuesto, int cantidadDeRepuestos, double total, double totalApagar) {
       this.fabrica = fabrica;
       this.repuesto = repuesto;
       this.precioDelRepuesto = precioDelRepuesto;
       this.cantidadDeRepuestos = cantidadDeRepuestos;
       this.total = total;
       this.totalApagar = totalApagar;
    }
   
    public Integer getIdComprobante() {
        return this.idComprobante;
    }
    
    public void setIdComprobante(Integer idComprobante) {
        this.idComprobante = idComprobante;
    }
    public Fabrica getFabrica() {
        return this.fabrica;
    }
    
    public void setFabrica(Fabrica fabrica) {
        this.fabrica = fabrica;
    }
    public Repuesto getRepuesto() {
        return this.repuesto;
    }
    
    public void setRepuesto(Repuesto repuesto) {
        this.repuesto = repuesto;
    }
    public double getPrecioDelRepuesto() {
        return this.precioDelRepuesto;
    }
    
    public void setPrecioDelRepuesto(double precioDelRepuesto) {
        this.precioDelRepuesto = precioDelRepuesto;
    }
    public int getCantidadDeRepuestos() {
        return this.cantidadDeRepuestos;
    }
    
    public void setCantidadDeRepuestos(int cantidadDeRepuestos) {
        this.cantidadDeRepuestos = cantidadDeRepuestos;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public double getTotalApagar() {
        return this.totalApagar;
    }
    
    public void setTotalApagar(double totalApagar) {
        this.totalApagar = totalApagar;
    }




}


