package modelo;
// Generated 30/01/2020 17:37:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fabrica generated by hbm2java
 */
public class Fabrica  implements java.io.Serializable {


     private Integer idfabrica;
     private String nombre;
     private String direccion;
     private Set ventas = new HashSet(0);
     private Set comprobantes = new HashSet(0);

    public Fabrica() {
    }

	
    public Fabrica(String nombre, String direccion) {
        this.nombre = nombre;
        this.direccion = direccion;
    }
    public Fabrica(String nombre, String direccion, Set ventas, Set comprobantes) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.ventas = ventas;
       this.comprobantes = comprobantes;
    }
   
    public Integer getIdfabrica() {
        return this.idfabrica;
    }
    
    public void setIdfabrica(Integer idfabrica) {
        this.idfabrica = idfabrica;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
    public Set getComprobantes() {
        return this.comprobantes;
    }
    
    public void setComprobantes(Set comprobantes) {
        this.comprobantes = comprobantes;
    }

    @Override
    public String toString() {
        return  idfabrica + " " + nombre;
    }
    
    




}


