package modelo;
// Generated 30/01/2020 17:37:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Repuesto generated by hbm2java
 */
public class Repuesto  implements java.io.Serializable {


     private Integer idrepuesto;
     private String nombre;
     private String codigo;
     private double precioDeLista;
     private int stockActual;
     private String estado;
     private Set ventas = new HashSet(0);
     private Set comprobantes = new HashSet(0);

    public Repuesto() {
    }

	
    public Repuesto(String nombre, String codigo, double precioDeLista, int stockActual, String estado) {
        this.nombre = nombre;
        this.codigo = codigo;
        this.precioDeLista = precioDeLista;
        this.stockActual = stockActual;
        this.estado = estado;
    }
    public Repuesto(String nombre, String codigo, double precioDeLista, int stockActual, String estado, Set ventas, Set comprobantes) {
       this.nombre = nombre;
       this.codigo = codigo;
       this.precioDeLista = precioDeLista;
       this.stockActual = stockActual;
       this.estado = estado;
       this.ventas = ventas;
       this.comprobantes = comprobantes;
    }
   
    public Integer getIdrepuesto() {
        return this.idrepuesto;
    }
    
    public void setIdrepuesto(Integer idrepuesto) {
        this.idrepuesto = idrepuesto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public double getPrecioDeLista() {
        return this.precioDeLista;
    }
    
    public void setPrecioDeLista(double precioDeLista) {
        this.precioDeLista = precioDeLista;
    }
    public int getStockActual() {
        return this.stockActual;
    }
    
    public void setStockActual(int stockActual) {
        this.stockActual = stockActual;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
    public Set getComprobantes() {
        return this.comprobantes;
    }
    
    public void setComprobantes(Set comprobantes) {
        this.comprobantes = comprobantes;
    }

    @Override
    public String toString() {
        return  idrepuesto + " " + nombre+" "+ " precio: "+ precioDeLista +" " +estado;
    }

  
    
    

  

   

  
    
    
    

  
    
    
    

   

  
    
    
    




}


