package modelo;
// Generated 30/01/2020 17:37:59 by Hibernate Tools 4.3.1



/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private Fabrica fabrica;
     private Repuesto repuesto;
     private double precioDelRepuesto;
     private int cantidadDeRepuestos;
     private double total;

    public Venta() {
    }

    public Venta(Fabrica fabrica, Repuesto repuesto, double precioDelRepuesto, int cantidadDeRepuestos, double total) {
       this.fabrica = fabrica;
       this.repuesto = repuesto;
       this.precioDelRepuesto = precioDelRepuesto;
       this.cantidadDeRepuestos = cantidadDeRepuestos;
       this.total = total;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Fabrica getFabrica() {
        return this.fabrica;
    }
    
    public void setFabrica(Fabrica fabrica) {
        this.fabrica = fabrica;
    }
    public Repuesto getRepuesto() {
        return this.repuesto;
    }
    
    public void setRepuesto(Repuesto repuesto) {
        this.repuesto = repuesto;
    }
    public double getPrecioDelRepuesto() {
        return this.precioDelRepuesto;
    }
    
    public void setPrecioDelRepuesto(double precioDelRepuesto) {
        this.precioDelRepuesto = precioDelRepuesto;
    }
    public int getCantidadDeRepuestos() {
        return this.cantidadDeRepuestos;
    }
    
    public void setCantidadDeRepuestos(int cantidadDeRepuestos) {
        this.cantidadDeRepuestos = cantidadDeRepuestos;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }




}


