/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaPrincipal;

import java.awt.Color;
import java.io.EOFException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;



/**
 *
 * @author pablo
 */
public class Vista extends javax.swing.JFrame {

   
    String apellido = "";
    int edad = 0;
    String nombre="";
   
   
  
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        setLocationRelativeTo(this);
     
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1apellido = new javax.swing.JTextField();
        jTextField3nombre = new javax.swing.JTextField();
        jRadioButton140 = new javax.swing.JRadioButton();
        jRadioButton241 = new javax.swing.JRadioButton();
        jRadioButton342 = new javax.swing.JRadioButton();
        jRadioButton450 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1MostrarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(682, 444));
        setMinimumSize(new java.awt.Dimension(770, 512));
        setPreferredSize(new java.awt.Dimension(780, 444));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(72, 53, 116, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(72, 103, 116, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Edad:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(72, 150, 116, 16);
        getContentPane().add(jTextField1apellido);
        jTextField1apellido.setBounds(194, 99, 176, 24);
        getContentPane().add(jTextField3nombre);
        jTextField3nombre.setBounds(194, 49, 176, 24);

        buttonGroup1.add(jRadioButton140);
        jRadioButton140.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton140.setText("40");
        getContentPane().add(jRadioButton140);
        jRadioButton140.setBounds(194, 144, 46, 28);

        buttonGroup1.add(jRadioButton241);
        jRadioButton241.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton241.setText("41");
        getContentPane().add(jRadioButton241);
        jRadioButton241.setBounds(273, 144, 46, 28);

        buttonGroup1.add(jRadioButton342);
        jRadioButton342.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton342.setText("42");
        getContentPane().add(jRadioButton342);
        jRadioButton342.setBounds(347, 144, 46, 28);

        buttonGroup1.add(jRadioButton450);
        jRadioButton450.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton450.setText("50");
        getContentPane().add(jRadioButton450);
        jRadioButton450.setBounds(424, 144, 46, 28);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(681, 440));

        jButton1MostrarDatos.setBackground(new java.awt.Color(0, 0, 0));
        jButton1MostrarDatos.setForeground(new java.awt.Color(255, 255, 255));
        jButton1MostrarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaPrincipal/icono open.png"))); // NOI18N
        jButton1MostrarDatos.setBorder(null);
        jButton1MostrarDatos.setBorderPainted(false);
        jButton1MostrarDatos.setContentAreaFilled(false);
        jButton1MostrarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1MostrarDatos.setIconTextGap(-3);
        jButton1MostrarDatos.setRolloverEnabled(true);
        jButton1MostrarDatos.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\pablo\\Desktop\\ICONOS\\ICONOS CAMBIADOS EL TAMAÑO\\open mas grande.png")); // NOI18N
        jButton1MostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1MostrarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jButton1MostrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(jButton1MostrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 4, 780, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1MostrarDatosActionPerformed
       
                
        try {
            mostrar();
        } catch (EOFException e) {
            JOptionPane.showMessageDialog(null, "casillero en blanco");
        }

    }//GEN-LAST:event_jButton1MostrarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public JTextField getjTextField1apellido() {
        return jTextField1apellido;
    }

    /**
     * @param args the command line arguments
     */
    public JTextField getjTextField3nombre() {
        return jTextField3nombre;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JRadioButton getjRadioButton140() {
        return jRadioButton140;
    }

    public JRadioButton getjRadioButton241() {
        return jRadioButton241;
    }

    public JRadioButton getjRadioButton342() {
        return jRadioButton342;
    }

    public JRadioButton getjRadioButton450() {
        return jRadioButton450;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    private void mostrar() throws EOFException {

        nombre = this.getjTextField3nombre().getText();
        apellido = this. getjTextField1apellido().getText();
       
            
        if(nombre.length()==0 || apellido.length()==0){
    
        
        throw new EOFException();
        
        }
        
       
        

        apellido = this.getjTextField1apellido().getText();

        this.getjRadioButton241().setActionCommand("41");
        this.getjRadioButton342().setActionCommand("42");
        this.getjRadioButton140().setActionCommand("40");
        this.getjRadioButton450().setActionCommand("50");

        edad = Integer.valueOf(this.getButtonGroup1().getSelection().getActionCommand());

        JOptionPane.showMessageDialog(null, "el nombre es "  +nombre + " el apellido es " + apellido + " y la edad es " + (edad + 100));
        
     
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1MostrarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton140;
    private javax.swing.JRadioButton jRadioButton241;
    private javax.swing.JRadioButton jRadioButton342;
    private javax.swing.JRadioButton jRadioButton450;
    private javax.swing.JTextField jTextField1apellido;
    private javax.swing.JTextField jTextField3nombre;
    // End of variables declaration//GEN-END:variables

}
