package modelo;
// Generated 10/05/2020 19:03:06 by Hibernate Tools 4.3.1



/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private String cliente;
     private String platosYbebidas;
     private String mesa;
     private double precio;
     private double cantidad;
     private String total;

    public Factura() {
    }

    public Factura(String cliente, String platosYbebidas, String mesa, double precio, double cantidad, String total) {
       this.cliente = cliente;
       this.platosYbebidas = platosYbebidas;
       this.mesa = mesa;
       this.precio = precio;
       this.cantidad = cantidad;
       this.total = total;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getPlatosYbebidas() {
        return this.platosYbebidas;
    }
    
    public void setPlatosYbebidas(String platosYbebidas) {
        this.platosYbebidas = platosYbebidas;
    }
    public String getMesa() {
        return this.mesa;
    }
    
    public void setMesa(String mesa) {
        this.mesa = mesa;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }




}


