package modelo;
// Generated 10/05/2020 19:03:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer idPedido;
     private Cliente cliente;
     private Mesa mesa;
     private Plato plato;
     private double demora;
     private double cantidad;
     private String estado;
     private Set propietarios = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(Cliente cliente, Mesa mesa, Plato plato, double demora, double cantidad, String estado) {
        this.cliente = cliente;
        this.mesa = mesa;
        this.plato = plato;
        this.demora = demora;
        this.cantidad = cantidad;
        this.estado = estado;
    }
    public Pedido(Cliente cliente, Mesa mesa, Plato plato, double demora, double cantidad, String estado, Set propietarios) {
       this.cliente = cliente;
       this.mesa = mesa;
       this.plato = plato;
       this.demora = demora;
       this.cantidad = cantidad;
       this.estado = estado;
       this.propietarios = propietarios;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public Plato getPlato() {
        return this.plato;
    }
    
    public void setPlato(Plato plato) {
        this.plato = plato;
    }
    public double getDemora() {
        return this.demora;
    }
    
    public void setDemora(double demora) {
        this.demora = demora;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getPropietarios() {
        return this.propietarios;
    }
    
    public void setPropietarios(Set propietarios) {
        this.propietarios = propietarios;
    }




}


