package modelo;
// Generated 28/03/2020 20:45:43 by Hibernate Tools 4.3.1



/**
 * Propietario generated by hbm2java
 */
public class Propietario  implements java.io.Serializable {


     private Integer idPropietario;
     private Factura factura;

    public Propietario() {
    }

    public Propietario(Factura factura) {
       this.factura = factura;
    }
   
    public Integer getIdPropietario() {
        return this.idPropietario;
    }
    
    public void setIdPropietario(Integer idPropietario) {
        this.idPropietario = idPropietario;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }




}


