/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import ejemplo_buscador_sakila.HibernateUtil;
import java.util.List;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Persona;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import presentador.Presentador;

/**
 *
 * @author pablo
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private Presentador presentador;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.presentador = new Presentador(this);
        setLocationRelativeTo(this);
        
    }
    
    // 1 definis la consulta pero no esta completa
private static String QUERY_BASED_ON_NOMBRE="from Persona a where a.nombre like '";
private static String QUERY_BASED_ON_APELLIDO="from Persona a where a.apellido like '";


private void runQueryBasedOnFirstName() {
    // 3 Esta funcion toma lo que definiste en el paso 1, y la completa, en este caso toma el NOMBRE y le agrega el simbolo % (es para que funcionae el like)
    // Por ejemplo, ingreso fede, me va a buscar todos los nombres que empiecen con fede por ejemplo: federico, federica. 
    // La consulta completa quedaria "from Actor a where a.firstName like 'fede%'"
    executeHQLQuery(QUERY_BASED_ON_NOMBRE + getjTextFieldNombre_buscar().getText() + "%'");
}
    
private void runQueryBasedOnLastName() {
    executeHQLQuery(QUERY_BASED_ON_APELLIDO + getjTextFieldapellido_buscar().getText() + "%'");
}





 private void executeHQLQuery(String hql) {
    try {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query q = session.createQuery(hql);
        List resultList = q.list();
        displayResult(resultList);
        session.getTransaction().commit();
    } catch (HibernateException he) {
        he.printStackTrace();
    }
}
 private void displayResult(List resultList) {
    Vector<String> tableHeaders = new Vector<String>();
    Vector tableData = new Vector();
    tableHeaders.add("id"); 
    tableHeaders.add("Nombre");
    tableHeaders.add("Apellido");
    tableHeaders.add("Edad");
    tableHeaders.add("Fecha");

    for(Object o : resultList) {
        Persona persona = (Persona)o;
        Vector<Object> oneRow = new Vector<Object>();
        oneRow.add(persona.getIdpersona());
        oneRow.add(persona.getNombre());
        oneRow.add(persona.getApellido());
        oneRow.add(persona.getEdad());
        oneRow.add(persona.getFecha());
        tableData.add(oneRow);
    }
    jTable_tabla_persona.setModel(new DefaultTableModel(tableData, tableHeaders));
}
    
    
   

    public JTextField getjTextFieldApellido() {
        return jTextFieldApellido;
    }

    public JTextField getjTextFieldEdad() {
        return jTextFieldEdad;
    }

    public JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    public JTextField getjTextFieldCiudad() {
        return jTextFieldCiudad;
    }

    public JTextField getjTextFieldFechaDelViaje() {
        return jTextFieldFechaDelViaje;
    }

    public JTextField getjTextFieldPais() {
        return jTextFieldPais;
    }

    public JTextField getjTextFiel_id_persona() {
        return jTextFiel_id_persona;
    }

    public JTable getjTable_tabla_persona() {
        return jTable_tabla_persona;
    }

    public JTextField getjTextFieldNombre_buscar() {
        return jTextFieldNombre_buscar;
    }

    public JTextField getjTextFieldapellido_buscar() {
        return jTextFieldapellido_buscar;
    }

    public JComboBox<Object> getjComboBoxPersonas() {
        return jComboBoxPersonas;
    }
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonGuardarPersona = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tabla_persona = new javax.swing.JTable();
        jButtonBuscarPersonas = new javax.swing.JButton();
        jTextFieldNombre_buscar = new javax.swing.JTextField();
        jTextFieldapellido_buscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldCiudad = new javax.swing.JTextField();
        jTextFieldPais = new javax.swing.JTextField();
        jTextFieldFechaDelViaje = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonGuardarViaje = new javax.swing.JButton();
        jTextFiel_id_persona = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxPersonas = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonMostrarViajesPorPersonas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(600, 50));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);
        jPanel1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(273, 11, 267, 29);
        jPanel1.add(jTextFieldApellido);
        jTextFieldApellido.setBounds(270, 50, 267, 30);
        jPanel1.add(jTextFieldEdad);
        jTextFieldEdad.setBounds(270, 90, 267, 29);

        jLabel1.setText("NOMBRE:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(161, 18, 70, 14);

        jLabel2.setText("APELLIDO:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 60, 70, 14);

        jLabel3.setText("EDAD:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 100, 61, 14);

        jButtonGuardarPersona.setText("Guardar");
        jButtonGuardarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarPersonaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardarPersona);
        jButtonGuardarPersona.setBounds(590, 43, 130, 40);

        jTable_tabla_persona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "nombre", "apellido", "edad", "fecha"
            }
        ));
        jScrollPane1.setViewportView(jTable_tabla_persona);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 600, 280);

        jButtonBuscarPersonas.setText("Buscar");
        jButtonBuscarPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarPersonas);
        jButtonBuscarPersonas.setBounds(670, 383, 90, 30);
        jPanel1.add(jTextFieldNombre_buscar);
        jTextFieldNombre_buscar.setBounds(650, 220, 110, 30);
        jPanel1.add(jTextFieldapellido_buscar);
        jTextFieldapellido_buscar.setBounds(650, 300, 110, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 140, 710, 10);

        jLabel8.setText("nombre");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(650, 180, 60, 14);

        jLabel9.setText("apellido");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(650, 270, 70, 14);

        jTabbedPane1.addTab("PERSONA", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(null);
        jPanel2.add(jTextFieldCiudad);
        jTextFieldCiudad.setBounds(240, 80, 231, 29);
        jPanel2.add(jTextFieldPais);
        jTextFieldPais.setBounds(240, 130, 231, 31);
        jPanel2.add(jTextFieldFechaDelViaje);
        jTextFieldFechaDelViaje.setBounds(240, 180, 231, 29);

        jLabel4.setText("CIUDAD:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 90, 112, 14);

        jLabel5.setText("PAIS:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(100, 140, 112, 14);

        jLabel6.setText("FECHA DEL VIAJE:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(100, 190, 128, 14);

        jButtonGuardarViaje.setText("Guardar");
        jButtonGuardarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarViajeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonGuardarViaje);
        jButtonGuardarViaje.setBounds(260, 240, 182, 41);
        jPanel2.add(jTextFiel_id_persona);
        jTextFiel_id_persona.setBounds(240, 30, 231, 30);

        jLabel7.setText("ID PERSONA:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(100, 40, 112, 14);

        jPanel2.add(jComboBoxPersonas);
        jComboBoxPersonas.setBounds(300, 330, 320, 30);

        jLabel10.setText("VIAJES DE LAS PERSONAS:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(90, 340, 160, 14);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(20, 302, 750, 10);

        jButtonMostrarViajesPorPersonas.setText("Mostrar");
        jButtonMostrarViajesPorPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarViajesPorPersonasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonMostrarViajesPorPersonas);
        jButtonMostrarViajesPorPersonas.setBounds(360, 390, 200, 40);

        jTabbedPane1.addTab("VIAJE", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarPersonaActionPerformed
       this.presentador.guardarPersonaApretado();
    }//GEN-LAST:event_jButtonGuardarPersonaActionPerformed

    private void jButtonGuardarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarViajeActionPerformed
       this.presentador.guardarViajeApretado();
    }//GEN-LAST:event_jButtonGuardarViajeActionPerformed

    private void jButtonBuscarPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPersonasActionPerformed
      //significa no vacio
        if(!jTextFieldNombre_buscar.getText().trim().equals("")) {
        runQueryBasedOnFirstName();
    } else if(!jTextFieldapellido_buscar.getText().trim().equals("")) {
        runQueryBasedOnLastName();
    } 
    }//GEN-LAST:event_jButtonBuscarPersonasActionPerformed

    private void jButtonMostrarViajesPorPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarViajesPorPersonasActionPerformed
      this.presentador.obtenerViajesPorPersona();
    }//GEN-LAST:event_jButtonMostrarViajesPorPersonasActionPerformed

    /**
     * @param args the command line arguments
     */

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarPersonas;
    private javax.swing.JButton jButtonGuardarPersona;
    private javax.swing.JButton jButtonGuardarViaje;
    private javax.swing.JButton jButtonMostrarViajesPorPersonas;
    private javax.swing.JComboBox<Object> jComboBoxPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_tabla_persona;
    private javax.swing.JTextField jTextFiel_id_persona;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldFechaDelViaje;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre_buscar;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldapellido_buscar;
    // End of variables declaration//GEN-END:variables
}
