package modelo;
// Generated 16/03/2019 18:55:18 by Hibernate Tools 4.3.1



/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private Integer idvendedor;
     private String nombre;
     private String apellido;
     private int edad;
     private double sueldo;

    public Vendedor() {
    }

    public Vendedor(String nombre, String apellido, int edad, double sueldo) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
       this.sueldo = sueldo;
    }
   
    public Integer getIdvendedor() {
        return this.idvendedor;
    }
    
    public void setIdvendedor(Integer idvendedor) {
        this.idvendedor = idvendedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public double getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(double sueldo) {
        this.sueldo = sueldo;
    }
    
    




}


