package modelo;
// Generated 02/05/2019 21:43:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bicicleta generated by hbm2java
 */
public class Bicicleta  implements java.io.Serializable {


     private Integer idbicicleta;
     private String tipo;
     private double costo;
     private double ganancia;
     private int stockActual;
     private Set detallecompras = new HashSet(0);

    public Bicicleta() {
    }

	
    public Bicicleta(String tipo, double costo, double ganancia, int stockActual) {
        this.tipo = tipo;
        this.costo = costo;
        this.ganancia = ganancia;
        this.stockActual = stockActual;
    }
    public Bicicleta(String tipo, double costo, double ganancia, int stockActual, Set detallecompras) {
       this.tipo = tipo;
       this.costo = costo;
       this.ganancia = ganancia;
       this.stockActual = stockActual;
       this.detallecompras = detallecompras;
    }
   
    public Integer getIdbicicleta() {
        return this.idbicicleta;
    }
    
    public void setIdbicicleta(Integer idbicicleta) {
        this.idbicicleta = idbicicleta;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public double getCosto() {
        return this.costo;
    }
    
    public void setCosto(double costo) {
        this.costo = costo;
    }
    public double getGanancia() {
        return this.ganancia;
    }
    
    public void setGanancia(double ganancia) {
        this.ganancia = ganancia;
    }
    public int getStockActual() {
        return this.stockActual;
    }
    
    public void setStockActual(int stockActual) {
        this.stockActual = stockActual;
    }
    public Set getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set detallecompras) {
        this.detallecompras = detallecompras;
    }

    @Override
    public String toString() {
        return  idbicicleta +" " + tipo + " costo "+ costo +" ganancia " + ganancia +" stock "+  stockActual;
    }
    
    
    
    




}


