package modelo;
// Generated 02/05/2019 21:43:13 by Hibernate Tools 4.3.1



/**
 * Detallecompra generated by hbm2java
 */
public class Detallecompra  implements java.io.Serializable {


     private Integer idDetalleCompra;
     private Bicicleta bicicleta;
     private Compra compra;
     private int cantidad;
     private double precioUnitario;

    public Detallecompra() {
    }

    public Detallecompra(Bicicleta bicicleta, Compra compra, int cantidad, double precioUnitario) {
       this.bicicleta = bicicleta;
       this.compra = compra;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
    }
   
    public Integer getIdDetalleCompra() {
        return this.idDetalleCompra;
    }
    
    public void setIdDetalleCompra(Integer idDetalleCompra) {
        this.idDetalleCompra = idDetalleCompra;
    }
    public Bicicleta getBicicleta() {
        return this.bicicleta;
    }
    
    public void setBicicleta(Bicicleta bicicleta) {
        this.bicicleta = bicicleta;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }




}


