package modelo;
// Generated 22/01/2019 17:53:56 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 * Album generated by hbm2java
 */
public class Album implements java.io.Serializable {

    private Integer idalbum;
    private String nombre;
    private int cantidadMaxima;
    private Set fotos = new HashSet(0);
    private List<Foto> fotos1;

    public Album() {
    }

    public Album(String nombre, int cantidadMaxima) {
        this.nombre = nombre;
        this.cantidadMaxima = cantidadMaxima;
    }

    public Album(String nombre, int cantidadMaxima, Set fotos) {
        this.nombre = nombre;
        this.cantidadMaxima = cantidadMaxima;
        this.fotos = fotos;
        this.fotos1 = new ArrayList<>();

    }

    public Integer getIdalbum() {
        return this.idalbum;
    }

    public void setIdalbum(Integer idalbum) {
        this.idalbum = idalbum;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getCantidadMaxima() {
        return this.cantidadMaxima;
    }

    public void setCantidadMaxima(int cantidadMaxima) {
        this.cantidadMaxima = cantidadMaxima;
    }

    public Set getFotos() {
        return this.fotos;
    }

    public void setFotos(Set fotos) {
        this.fotos = fotos;
    }

    public List<Foto> getFotos1() {
        return fotos1;
    }

    public void addFoto(Foto foto) {

        this.fotos1.add(foto);
      

    }
   

    @Override
    public String toString() {
        return "id album:" + idalbum + ", nombre:" + nombre + ", cantidad Maxima:" + cantidadMaxima + fotos1;

    }

}
