package modelo;
// Generated 22/01/2019 17:53:56 by Hibernate Tools 4.3.1

/**
 * Foto generated by hbm2java
 */
public class Foto implements java.io.Serializable {

    private Integer idfoto;
    private Album album;
    private String nombreArchivo;
    private int tamaño;
    private String descripcion;

    public Foto() {
    }

    public Foto(Album album, String nombreArchivo, int tamaño, String descripcion) {
        this.album = album;
        this.nombreArchivo = nombreArchivo;
        this.tamaño = tamaño;
        this.descripcion = descripcion;

    }

    public Integer getIdfoto() {
        return this.idfoto;
    }

    public void setIdfoto(Integer idfoto) {
        this.idfoto = idfoto;
    }

    public Album getAlbum() {
        return this.album;
    }

    public void setAlbum(Album album) {
        this.album = album;
    }

    public String getNombreArchivo() {
        return this.nombreArchivo;
    }

    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }

    public int getTamaño() {
        return this.tamaño;
    }

    public void setTamaño(int tamaño) {
        this.tamaño = tamaño;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public void addFoto(Foto foto) {

        this.album.getFotos1().add(foto);

    }

    @Override
    public String toString() {
        return "Foto{" + "nombreArchivo=" + nombreArchivo + ", tama\u00f1o=" + tamaño + '}';
    }

}
