/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaPrincipal;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelo.Repuesto;
import presentador.Presentador;

/**
 *
 * @author pablo
 */
public class VistaPrincipal extends javax.swing.JFrame {
    private Presentador presentador;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.presentador = new Presentador(this);
        setLocationRelativeTo(this);
    }

    public JTextField getjTextField2Codigo() {
        return jTextField2Codigo;
    }

    public JTextField getjTextField3PrecioDeLista_repuesto() {
        return jTextField3PrecioDeLista_repuesto;
    }

    public JTextField getjTextField4StockActual() {
        return jTextField4StockActual;
    }

    public JTextField getjTextField5StockMinimo() {
        return jTextField5StockMinimo;
    }

    public JTextField getjTextField1nombre_nombreRepuesto() {
        return jTextField1nombre_nombreRepuesto;
    }

   

    public JTextField getjTextField1CantidadDeRepuestos_fabrica() {
        return jTextField1CantidadDeRepuestos_fabrica;
    }

    public JTextField getjTextField2PrecioConIva_fabrica() {
        return jTextField2PrecioConIva_fabrica;
    }

    public JTextField getjTextField3Total_fabrica() {
        return jTextField3Total_fabrica;
    }

    public JTextField getjTextField4CostoDeEnvio() {
        return jTextField4CostoDeEnvio;
    }

    public JTextField getjTextField5Direccion() {
        return jTextField5Direccion;
    }

    public JTextField getjTextField6NombreFabrica() {
        return jTextField6NombreFabrica;
    }

    public JTextField getjTextField1Cantidad_comprobante() {
        return jTextField1Cantidad_comprobante;
    }

    public JTextField getjTextField2precioUnitarioConIva_comprobante() {
        return jTextField2precioUnitarioConIva_comprobante;
    }

    public JTextField getjTextField3total_comprobante() {
        return jTextField3total_comprobante;
    }

    public JTextField getjTextField4TotalApagar_comprobante() {
        return jTextField4TotalApagar_comprobante;
    }

    public JComboBox<Object> getjComboBox1Repuesto_Fabrica() {
        return jComboBox1Repuesto_Fabrica;
    }

    public JTextField getjTextField1Fabrica_comprobante() {
        return jTextField1Fabrica_comprobante;
    }

    public JComboBox<Object> getjComboBox1Repuesto_comprobante() {
        return jComboBox1Repuesto_comprobante;
    }

    public JComboBox<Object> getjComboBox1nombre_Repuesto() {
        return jComboBox1nombre_Repuesto;
    }

    public JTextField getjTextField1NombreEmpleado_repuesto() {
        return jTextField1NombreEmpleado_repuesto;
    }

    public JTable getjTable1Repuestos() {
        return jTable1Repuestos;
    }

    public JComboBox<Object> getjComboBox1Fabrica_comprobante() {
        return jComboBox1Fabrica_comprobante;
    }

    public JTextField getjTextField1CargarStock() {
        return jTextField1CargarStock;
    }

    public JTextField getjTextField2idCargarStock() {
        return jTextField2idCargarStock;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1nombre_nombreRepuesto = new javax.swing.JTextField();
        jButton1guardarNombre_nombreRepuesto = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2Codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3PrecioDeLista_repuesto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4StockActual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5StockMinimo = new javax.swing.JTextField();
        jButton1GuardarRepuesto = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1nombre_Repuesto = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jTextField1NombreEmpleado_repuesto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Repuestos = new javax.swing.JTable();
        jButton1CargarTabla = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTextField2idCargarStock = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField1CargarStock = new javax.swing.JTextField();
        jButton2CargarStock = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1CantidadDeRepuestos_fabrica = new javax.swing.JTextField();
        jTextField2PrecioConIva_fabrica = new javax.swing.JTextField();
        jTextField3Total_fabrica = new javax.swing.JTextField();
        jTextField4CostoDeEnvio = new javax.swing.JTextField();
        jTextField5Direccion = new javax.swing.JTextField();
        jTextField6NombreFabrica = new javax.swing.JTextField();
        jButton1Guardar_fabrica = new javax.swing.JButton();
        jComboBox1Repuesto_Fabrica = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jButton1calcularTotalFabrica = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1Cantidad_comprobante = new javax.swing.JTextField();
        jTextField2precioUnitarioConIva_comprobante = new javax.swing.JTextField();
        jTextField3total_comprobante = new javax.swing.JTextField();
        jTextField4TotalApagar_comprobante = new javax.swing.JTextField();
        jButton1GuardarComprobante = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField1Fabrica_comprobante = new javax.swing.JTextField();
        jComboBox1Fabrica_comprobante = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1Repuesto_comprobante = new javax.swing.JComboBox<>();
        jButton1CalcularTotalAPagar = new javax.swing.JButton();
        jButton1LimpiarTabla = new javax.swing.JButton();
        jButton1GenerarComprobante = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(600, 835));

        jPanel4.setLayout(null);

        jLabel1.setText("NOMBRE DEL REPUESTO:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(54, 88, 168, 14);
        jPanel4.add(jTextField1nombre_nombreRepuesto);
        jTextField1nombre_nombreRepuesto.setBounds(250, 80, 248, 30);

        jButton1guardarNombre_nombreRepuesto.setText("Guardar");
        jButton1guardarNombre_nombreRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1guardarNombre_nombreRepuestoActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1guardarNombre_nombreRepuesto);
        jButton1guardarNombre_nombreRepuesto.setBounds(320, 140, 127, 30);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaPrincipal/panatalla_final.jpg"))); // NOI18N
        jPanel4.add(jLabel22);
        jLabel22.setBounds(0, 0, 820, 480);

        jTabbedPane1.addTab("NOMBRE REPUESTO", jPanel4);

        jPanel1.setLayout(null);

        jLabel2.setText("CODIGO:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 80, 53, 14);
        jPanel1.add(jTextField2Codigo);
        jTextField2Codigo.setBounds(210, 70, 285, 30);

        jLabel3.setText("PRECIO DE LISTA:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 120, 127, 14);
        jPanel1.add(jTextField3PrecioDeLista_repuesto);
        jTextField3PrecioDeLista_repuesto.setBounds(210, 110, 285, 30);

        jLabel4.setText("STOCK ACTUAL:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 160, 117, 14);
        jPanel1.add(jTextField4StockActual);
        jTextField4StockActual.setBounds(210, 150, 285, 30);

        jLabel5.setText("STOCK MINIMO:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 200, 117, 14);
        jPanel1.add(jTextField5StockMinimo);
        jTextField5StockMinimo.setBounds(210, 190, 285, 30);

        jButton1GuardarRepuesto.setText("Guardar");
        jButton1GuardarRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GuardarRepuestoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1GuardarRepuesto);
        jButton1GuardarRepuesto.setBounds(590, 30, 159, 30);

        jLabel19.setText("NOMBRE REPUESTO:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(40, 40, 127, 14);

        jPanel1.add(jComboBox1nombre_Repuesto);
        jComboBox1nombre_Repuesto.setBounds(210, 30, 285, 30);

        jLabel20.setText("NOMBRE EMPLEADO:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(40, 240, 127, 14);
        jPanel1.add(jTextField1NombreEmpleado_repuesto);
        jTextField1NombreEmpleado_repuesto.setBounds(210, 230, 285, 30);

        jTable1Repuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre Repuesto", "Codigo", "Precio De Lista", "Stock Actual", "Stock Minimo", "Nombre Empleado"
            }
        ));
        jScrollPane1.setViewportView(jTable1Repuestos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 290, 760, 180);

        jButton1CargarTabla.setText("Cargar Tabla");
        jButton1CargarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CargarTablaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1CargarTabla);
        jButton1CargarTabla.setBounds(590, 80, 160, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("id:");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(570, 160, 20, 14);
        jPanel1.add(jTextField2idCargarStock);
        jTextField2idCargarStock.setBounds(610, 150, 40, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("stock");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(550, 200, 120, 22);
        jPanel1.add(jTextField1CargarStock);
        jTextField1CargarStock.setBounds(610, 190, 120, 30);

        jButton2CargarStock.setText("Actualizar stock");
        jButton2CargarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CargarStockActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2CargarStock);
        jButton2CargarStock.setBounds(600, 240, 140, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(550, 130, 250, 10);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaPrincipal/panatalla_final.jpg"))); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(0, 0, 820, 480);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("id:");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(570, 190, 20, 14);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("id:");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(570, 190, 20, 14);

        jTabbedPane1.addTab("REPUESTO", jPanel1);

        jPanel2.setLayout(null);

        jLabel6.setText("NOMBRE");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(120, 40, 92, 14);

        jLabel7.setText("DIRECCION:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(120, 80, 81, 14);

        jLabel8.setText("COSTO DE ENVIO:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(120, 120, 133, 14);

        jLabel9.setText("INTRODUZCA EL PRECIO DE LISTA:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(60, 250, 212, 14);

        jLabel10.setText("CANTIDAD DE REPUESTOS:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(73, 210, 180, 14);

        jLabel11.setText("TOTAL CON IVA:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(140, 284, 118, 20);
        jPanel2.add(jTextField1CantidadDeRepuestos_fabrica);
        jTextField1CantidadDeRepuestos_fabrica.setBounds(290, 200, 190, 30);
        jPanel2.add(jTextField2PrecioConIva_fabrica);
        jTextField2PrecioConIva_fabrica.setBounds(290, 240, 190, 30);
        jPanel2.add(jTextField3Total_fabrica);
        jTextField3Total_fabrica.setBounds(290, 280, 190, 30);
        jPanel2.add(jTextField4CostoDeEnvio);
        jTextField4CostoDeEnvio.setBounds(290, 110, 190, 30);
        jPanel2.add(jTextField5Direccion);
        jTextField5Direccion.setBounds(290, 70, 190, 30);
        jPanel2.add(jTextField6NombreFabrica);
        jTextField6NombreFabrica.setBounds(290, 30, 190, 30);

        jButton1Guardar_fabrica.setText("Guardar");
        jButton1Guardar_fabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1Guardar_fabricaActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1Guardar_fabrica);
        jButton1Guardar_fabrica.setBounds(30, 370, 171, 30);

        jPanel2.add(jComboBox1Repuesto_Fabrica);
        jComboBox1Repuesto_Fabrica.setBounds(288, 151, 226, 30);

        jLabel16.setText("REPUESTO:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(120, 160, 113, 14);

        jButton1calcularTotalFabrica.setText("Calcular total con iva incluido");
        jButton1calcularTotalFabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1calcularTotalFabricaActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1calcularTotalFabrica);
        jButton1calcularTotalFabrica.setBounds(260, 370, 200, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaPrincipal/panatalla_final.jpg"))); // NOI18N
        jPanel2.add(jLabel23);
        jLabel23.setBounds(0, 0, 820, 480);

        jTabbedPane1.addTab("FABRICA", jPanel2);

        jPanel3.setLayout(null);

        jLabel12.setText("CANTIDAD:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(120, 170, 140, 14);

        jLabel13.setText("PRECIO UNITARIO CON IVA:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(70, 130, 200, 14);

        jLabel14.setText("TOTAL:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(130, 210, 140, 14);

        jLabel15.setText("TOTAL A PAGAR:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(130, 250, 140, 14);
        jPanel3.add(jTextField1Cantidad_comprobante);
        jTextField1Cantidad_comprobante.setBounds(300, 160, 223, 30);
        jPanel3.add(jTextField2precioUnitarioConIva_comprobante);
        jTextField2precioUnitarioConIva_comprobante.setBounds(300, 120, 223, 30);
        jPanel3.add(jTextField3total_comprobante);
        jTextField3total_comprobante.setBounds(300, 200, 223, 30);
        jPanel3.add(jTextField4TotalApagar_comprobante);
        jTextField4TotalApagar_comprobante.setBounds(300, 240, 223, 30);

        jButton1GuardarComprobante.setText("Guardar");
        jButton1GuardarComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GuardarComprobanteActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1GuardarComprobante);
        jButton1GuardarComprobante.setBounds(40, 320, 130, 30);

        jLabel17.setText("FABRICA  ID:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(130, 50, 140, 14);
        jPanel3.add(jTextField1Fabrica_comprobante);
        jTextField1Fabrica_comprobante.setBounds(300, 40, 223, 30);

        jPanel3.add(jComboBox1Fabrica_comprobante);
        jComboBox1Fabrica_comprobante.setBounds(36, 390, 750, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("FABRICAS");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(350, 430, 100, 22);

        jLabel18.setText("REPUESTO:");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(130, 90, 140, 14);

        jPanel3.add(jComboBox1Repuesto_comprobante);
        jComboBox1Repuesto_comprobante.setBounds(300, 78, 223, 30);

        jButton1CalcularTotalAPagar.setText("Calcular Total a Pagar");
        jButton1CalcularTotalAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CalcularTotalAPagarActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1CalcularTotalAPagar);
        jButton1CalcularTotalAPagar.setBounds(230, 320, 170, 30);

        jButton1LimpiarTabla.setText("Limpiar tabla");
        jButton1LimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LimpiarTablaActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1LimpiarTabla);
        jButton1LimpiarTabla.setBounds(640, 320, 140, 30);

        jButton1GenerarComprobante.setText("Generar Comprobante");
        jButton1GenerarComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GenerarComprobanteActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1GenerarComprobante);
        jButton1GenerarComprobante.setBounds(430, 320, 190, 30);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaPrincipal/panatalla_final.jpg"))); // NOI18N
        jPanel3.add(jLabel25);
        jLabel25.setBounds(0, 0, 820, 480);

        jTabbedPane1.addTab("COMPROBANTE", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1GuardarRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GuardarRepuestoActionPerformed
       this.presentador.guardarRepuestoApretado();
    }//GEN-LAST:event_jButton1GuardarRepuestoActionPerformed

    private void jButton1Guardar_fabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1Guardar_fabricaActionPerformed
        this.presentador.guardarFabricaApretado();
    }//GEN-LAST:event_jButton1Guardar_fabricaActionPerformed

    private void jButton1GuardarComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GuardarComprobanteActionPerformed
       this.presentador.guardarComprobanteApretado();
    }//GEN-LAST:event_jButton1GuardarComprobanteActionPerformed

    private void jButton1guardarNombre_nombreRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1guardarNombre_nombreRepuestoActionPerformed
       this.presentador.guardarNombre_Apretado();
    }//GEN-LAST:event_jButton1guardarNombre_nombreRepuestoActionPerformed

    private void jButton1CargarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CargarTablaActionPerformed
       this.presentador.cargarTablaApretado();
    }//GEN-LAST:event_jButton1CargarTablaActionPerformed

    private void jButton1calcularTotalFabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1calcularTotalFabricaActionPerformed
       this.presentador.calcularTotalFabricaApretado();
    }//GEN-LAST:event_jButton1calcularTotalFabricaActionPerformed

    private void jButton2CargarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CargarStockActionPerformed
         int id = Integer.valueOf(jTextField2idCargarStock.getText());
        int stock = Integer.valueOf(jTextField1CargarStock.getText());

        Conexion conexion = new Conexion();
        Connection con = conexion.getConexion();
        
        Repuesto repuesto = this.presentador.obtenerRepuesto(id);
        
        int stockActuall = repuesto.getStockActual();
        int total = stock+stockActuall;
        
        

      

        String sql = "UPDATE repuesto SET  stockActual= '" + total + "' WHERE  idrepuesto='" + id + "'";

        try {
            PreparedStatement preparedStatement = con.prepareStatement(sql);
            preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(null, "el stock se actualizo correctamente");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton2CargarStockActionPerformed

    private void jButton1CalcularTotalAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CalcularTotalAPagarActionPerformed
       this.presentador.calcularTotalAPagar();
    }//GEN-LAST:event_jButton1CalcularTotalAPagarActionPerformed

    private void jButton1LimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LimpiarTablaActionPerformed
       this.presentador.limpiarTablaApretado();
    }//GEN-LAST:event_jButton1LimpiarTablaActionPerformed

    private void jButton1GenerarComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GenerarComprobanteActionPerformed
       this.presentador.generarComprobanteApretado();
    }//GEN-LAST:event_jButton1GenerarComprobanteActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
    
    
    
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1CalcularTotalAPagar;
    private javax.swing.JButton jButton1CargarTabla;
    private javax.swing.JButton jButton1GenerarComprobante;
    private javax.swing.JButton jButton1GuardarComprobante;
    private javax.swing.JButton jButton1GuardarRepuesto;
    private javax.swing.JButton jButton1Guardar_fabrica;
    private javax.swing.JButton jButton1LimpiarTabla;
    private javax.swing.JButton jButton1calcularTotalFabrica;
    private javax.swing.JButton jButton1guardarNombre_nombreRepuesto;
    private javax.swing.JButton jButton2CargarStock;
    private javax.swing.JComboBox<Object> jComboBox1Fabrica_comprobante;
    private javax.swing.JComboBox<Object> jComboBox1Repuesto_Fabrica;
    private javax.swing.JComboBox<Object> jComboBox1Repuesto_comprobante;
    private javax.swing.JComboBox<Object> jComboBox1nombre_Repuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1Repuestos;
    private javax.swing.JTextField jTextField1CantidadDeRepuestos_fabrica;
    private javax.swing.JTextField jTextField1Cantidad_comprobante;
    private javax.swing.JTextField jTextField1CargarStock;
    private javax.swing.JTextField jTextField1Fabrica_comprobante;
    private javax.swing.JTextField jTextField1NombreEmpleado_repuesto;
    private javax.swing.JTextField jTextField1nombre_nombreRepuesto;
    private javax.swing.JTextField jTextField2Codigo;
    private javax.swing.JTextField jTextField2PrecioConIva_fabrica;
    private javax.swing.JTextField jTextField2idCargarStock;
    private javax.swing.JTextField jTextField2precioUnitarioConIva_comprobante;
    private javax.swing.JTextField jTextField3PrecioDeLista_repuesto;
    private javax.swing.JTextField jTextField3Total_fabrica;
    private javax.swing.JTextField jTextField3total_comprobante;
    private javax.swing.JTextField jTextField4CostoDeEnvio;
    private javax.swing.JTextField jTextField4StockActual;
    private javax.swing.JTextField jTextField4TotalApagar_comprobante;
    private javax.swing.JTextField jTextField5Direccion;
    private javax.swing.JTextField jTextField5StockMinimo;
    private javax.swing.JTextField jTextField6NombreFabrica;
    // End of variables declaration//GEN-END:variables
}


