/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaPrincipal;

import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import presentador.Presentador;

/**
 *
 * @author pablo
 */
public class PedidoVista extends javax.swing.JFrame {
      private Presentador presentador;
    /**
     * Creates new form Pedido
     */
    public PedidoVista() {
        initComponents();
        setLocationRelativeTo(this);
        this.presentador = new Presentador(this);
        jRadioButton1activo_pedido.setSelected(true);
    }

    public JComboBox<Object> getjComboBox1mesa_pedido() {
        return jComboBox1mesa_pedido;
    }

    public JComboBox<Object> getjComboBox2cliente_pedido() {
        return jComboBox2cliente_pedido;
    }

    public JComboBox<Object> getjComboBox3comestible_pedido() {
        return jComboBox3comestible_pedido;
    }

    public JComboBox<Object> getjComboBox1tipo_pedido() {
        return jComboBox1tipo_pedido;
    }

    public JTable getjTable1pedido_pedido() {
        return jTable1pedido_pedido;
    }

    public JRadioButton getjRadioButton1activo_pedido() {
        return jRadioButton1activo_pedido;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }
    
    
    
    
    
    

    

    

    public JTextField getjTextField2demora_pedido() {
        return jTextField2demora_pedido;
    }

    public JTextField getjTextField3cantidad_pedido() {
        return jTextField3cantidad_pedido;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jButton1salirPedido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1mesa_pedido = new javax.swing.JComboBox<>();
        jComboBox2cliente_pedido = new javax.swing.JComboBox<>();
        jComboBox3comestible_pedido = new javax.swing.JComboBox<>();
        jTextField2demora_pedido = new javax.swing.JTextField();
        jTextField3cantidad_pedido = new javax.swing.JTextField();
        jButton1guardarPedido = new javax.swing.JButton();
        jComboBox1tipo_pedido = new javax.swing.JComboBox<>();
        jButton1botonAgregarComestibles = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1pedido_pedido = new javax.swing.JTable();
        jRadioButton1activo_pedido = new javax.swing.JRadioButton();
        jButton1cargarTabla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("PedidoVistas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1015, 610));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PEDIDO.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 130, 140);

        jButton1salirPedido.setBackground(new java.awt.Color(0, 0, 0));
        jButton1salirPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1salirPedido.setForeground(new java.awt.Color(255, 255, 255));
        jButton1salirPedido.setText("Salir");
        jButton1salirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1salirPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1salirPedido);
        jButton1salirPedido.setBounds(880, 490, 90, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Estado:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(770, 80, 60, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cliente:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 20, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mesa:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 80, 50, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Comestible:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 20, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Demora:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 80, 70, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 80, 80, 30);

        jComboBox1mesa_pedido.setComponentPopupMenu(jPopupMenu1);
        getContentPane().add(jComboBox1mesa_pedido);
        jComboBox1mesa_pedido.setBounds(400, 80, 160, 30);

        getContentPane().add(jComboBox2cliente_pedido);
        jComboBox2cliente_pedido.setBounds(240, 20, 190, 30);

        getContentPane().add(jComboBox3comestible_pedido);
        jComboBox3comestible_pedido.setBounds(530, 20, 210, 30);
        getContentPane().add(jTextField2demora_pedido);
        jTextField2demora_pedido.setBounds(650, 80, 80, 30);
        getContentPane().add(jTextField3cantidad_pedido);
        jTextField3cantidad_pedido.setBounds(260, 80, 70, 30);

        jButton1guardarPedido.setBackground(new java.awt.Color(0, 0, 0));
        jButton1guardarPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1guardarPedido.setForeground(new java.awt.Color(255, 255, 255));
        jButton1guardarPedido.setText("Guardar");
        jButton1guardarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1guardarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1guardarPedido);
        jButton1guardarPedido.setBounds(720, 490, 130, 40);

        getContentPane().add(jComboBox1tipo_pedido);
        jComboBox1tipo_pedido.setBounds(750, 20, 100, 30);

        jButton1botonAgregarComestibles.setBackground(new java.awt.Color(0, 0, 0));
        jButton1botonAgregarComestibles.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1botonAgregarComestibles.setForeground(new java.awt.Color(255, 255, 255));
        jButton1botonAgregarComestibles.setText("Agregar");
        jButton1botonAgregarComestibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1botonAgregarComestiblesActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1botonAgregarComestibles);
        jButton1botonAgregarComestibles.setBounds(870, 20, 100, 30);

        jTable1pedido_pedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "cliente", "mesa", "comestible", "cantidad", "demora", "estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1pedido_pedido);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 170, 780, 290);

        buttonGroup1.add(jRadioButton1activo_pedido);
        jRadioButton1activo_pedido.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jRadioButton1activo_pedido.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1activo_pedido.setText("Activo");
        getContentPane().add(jRadioButton1activo_pedido);
        jRadioButton1activo_pedido.setBounds(860, 80, 110, 25);

        jButton1cargarTabla.setBackground(new java.awt.Color(0, 0, 0));
        jButton1cargarTabla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1cargarTabla.setForeground(new java.awt.Color(255, 255, 255));
        jButton1cargarTabla.setText("Cargar tabla");
        jButton1cargarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1cargarTablaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1cargarTabla);
        jButton1cargarTabla.setBounds(190, 490, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo rojo pizzeria2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -60, 1010, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1salirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1salirPedidoActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1salirPedidoActionPerformed

    private void jButton1guardarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1guardarPedidoActionPerformed
       this.presentador.guardarPedidoApretado();
    }//GEN-LAST:event_jButton1guardarPedidoActionPerformed

    private void jButton1botonAgregarComestiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1botonAgregarComestiblesActionPerformed
       this.presentador.agregarComestiblesApretado();
    }//GEN-LAST:event_jButton1botonAgregarComestiblesActionPerformed

    private void jButton1cargarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1cargarTablaActionPerformed
       this.presentador.cargarTablaPedido();
    }//GEN-LAST:event_jButton1cargarTablaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       this.presentador.llenarComboMesasPedido();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1botonAgregarComestibles;
    private javax.swing.JButton jButton1cargarTabla;
    private javax.swing.JButton jButton1guardarPedido;
    private javax.swing.JButton jButton1salirPedido;
    private javax.swing.JComboBox<Object> jComboBox1mesa_pedido;
    private javax.swing.JComboBox<Object> jComboBox1tipo_pedido;
    private javax.swing.JComboBox<Object> jComboBox2cliente_pedido;
    private javax.swing.JComboBox<Object> jComboBox3comestible_pedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1activo_pedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1pedido_pedido;
    private javax.swing.JTextField jTextField2demora_pedido;
    private javax.swing.JTextField jTextField3cantidad_pedido;
    // End of variables declaration//GEN-END:variables
}
