package modelo;
// Generated 19/10/2019 15:46:25 by Hibernate Tools 4.3.1



/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private Integer idDetalle;
     private Repuesto repuesto;
     private Ventas ventas;
     private double precioUnitarioConIva;
     private int cantidad;

    public DetalleVenta() {
    }

    public DetalleVenta(Repuesto repuesto, Ventas ventas, double precioUnitarioConIva, int cantidad) {
       this.repuesto = repuesto;
       this.ventas = ventas;
       this.precioUnitarioConIva = precioUnitarioConIva;
       this.cantidad = cantidad;
    }
   
    public Integer getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(Integer idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Repuesto getRepuesto() {
        return this.repuesto;
    }
    
    public void setRepuesto(Repuesto repuesto) {
        this.repuesto = repuesto;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public double getPrecioUnitarioConIva() {
        return this.precioUnitarioConIva;
    }
    
    public void setPrecioUnitarioConIva(double precioUnitarioConIva) {
        this.precioUnitarioConIva = precioUnitarioConIva;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
  




}


