package modelo;
// Generated 19/10/2019 15:46:25 by Hibernate Tools 4.3.1



/**
 * Fabricas generated by hbm2java
 */
public class Fabricas  implements java.io.Serializable {


     private Integer idfabricas;
     private Repuesto repuesto;
     private String nombre;
     private String localidad;
     private double costoDelEnvio;
     private String necesitaEnvio;
     private String efectuoElpago;

    public Fabricas() {
    }

    public Fabricas(Repuesto repuesto, String nombre, String localidad, double costoDelEnvio, String necesitaEnvio, String efectuoElpago) {
       this.repuesto = repuesto;
       this.nombre = nombre;
       this.localidad = localidad;
       this.costoDelEnvio = costoDelEnvio;
       this.necesitaEnvio = necesitaEnvio;
       this.efectuoElpago = efectuoElpago;
    }
   
    public Integer getIdfabricas() {
        return this.idfabricas;
    }
    
    public void setIdfabricas(Integer idfabricas) {
        this.idfabricas = idfabricas;
    }
    public Repuesto getRepuesto() {
        return this.repuesto;
    }
    
    public void setRepuesto(Repuesto repuesto) {
        this.repuesto = repuesto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public double getCostoDelEnvio() {
        return this.costoDelEnvio;
    }
    
    public void setCostoDelEnvio(double costoDelEnvio) {
        this.costoDelEnvio = costoDelEnvio;
    }
    public String getNecesitaEnvio() {
        return this.necesitaEnvio;
    }
    
    public void setNecesitaEnvio(String necesitaEnvio) {
        this.necesitaEnvio = necesitaEnvio;
    }
    public String getEfectuoElpago() {
        return this.efectuoElpago;
    }
    
    public void setEfectuoElpago(String efectuoElpago) {
        this.efectuoElpago = efectuoElpago;
    }




}


