package modelo;
// Generated 19/10/2019 15:46:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private Integer idproveedores;
     private String nombre;
     private String direccion;
     private Set repuestos = new HashSet(0);

    public Proveedores() {
    }

	
    public Proveedores(String nombre, String direccion) {
        this.nombre = nombre;
        this.direccion = direccion;
    }
    public Proveedores(String nombre, String direccion, Set repuestos) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.repuestos = repuestos;
    }
   
    public Integer getIdproveedores() {
        return this.idproveedores;
    }
    
    public void setIdproveedores(Integer idproveedores) {
        this.idproveedores = idproveedores;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getRepuestos() {
        return this.repuestos;
    }
    
    public void setRepuestos(Set repuestos) {
        this.repuestos = repuestos;
    }

    @Override
    public String toString() {
        return  idproveedores +" "+  nombre +" "+ direccion;
    }
    
    
    




}


