package modelo;
// Generated 19/10/2019 15:46:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private Integer idventas;
     private Repuesto repuesto;
     private Date fecha;
     private double montoTotalConIva;
     private String efectuoElPago;
     private Set detalleVentas = new HashSet(0);
     
    

    public Ventas() {
    }

	
    public Ventas(Repuesto repuesto, Date fecha, double montoTotalConIva, String efectuoElPago) {
        this.repuesto = repuesto;
        this.fecha = fecha;
        this.montoTotalConIva = montoTotalConIva;
        this.efectuoElPago = efectuoElPago;
    }
    public Ventas(Repuesto repuesto, Date fecha, double montoTotalConIva, String efectuoElPago, Set detalleVentas) {
       this.repuesto = repuesto;
       this.fecha = fecha;
       this.montoTotalConIva = montoTotalConIva;
       this.efectuoElPago = efectuoElPago;
       this.detalleVentas = detalleVentas;
    }
   
    public Integer getIdventas() {
        return this.idventas;
    }
    
    public void setIdventas(Integer idventas) {
        this.idventas = idventas;
    }
    public Repuesto getRepuesto() {
        return this.repuesto;
    }
    
    public void setRepuesto(Repuesto repuesto) {
        this.repuesto = repuesto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getMontoTotalConIva() {
        return this.montoTotalConIva;
    }
    
    public void setMontoTotalConIva(double montoTotalConIva) {
        this.montoTotalConIva = montoTotalConIva;
    }
    public String getEfectuoElPago() {
        return this.efectuoElPago;
    }
    
    public void setEfectuoElPago(String efectuoElPago) {
        this.efectuoElPago = efectuoElPago;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }
    
    
    
    
    
    




}


