package modelo;
// Generated 14/02/2022 12:00:12 by Hibernate Tools 4.3.1



/**
 * TotalString generated by hbm2java
 */
public class TotalString  implements java.io.Serializable {


     private Integer idtotalString;
     private String total;

    public TotalString() {
    }

    public TotalString(String total) {
       this.total = total;
    }
   
    public Integer getIdtotalString() {
        return this.idtotalString;
    }
    
    public void setIdtotalString(Integer idtotalString) {
        this.idtotalString = idtotalString;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }




}


