/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelo.DetalleVenta;
import modelo.Repuesto;
import presentador.Presentador;

/**
 *
 * @author pablo
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private Presentador presentador;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.presentador = new Presentador(this);
        this.jRadioButton1.setSelected(true);

    }

    public JTextField getDireccion_proveedor() {
        return direccion_proveedor;
    }

    public JTextField getNombre_proveedor() {
        return nombre_proveedor;
    }

    public JTextField getjTextField1NOMBRE_RESPUESTO() {
        return jTextField1NOMBRE_RESPUESTO;
    }

    public JTextField getjTextField2CODIGO_RESPUESTO() {
        return jTextField2CODIGO_RESPUESTO;
    }

    public JTextField getjTextField3STOCK_ACTUAL_RESPUESTO() {
        return jTextField3STOCK_ACTUAL_RESPUESTO;
    }

    public JTextField getjTextField4PRECIO_RESPUESTO() {
        return jTextField4PRECIO_RESPUESTO;
    }

    public JTextField getjTextField5STOCK_MINIMO_RESPUESTO() {
        return jTextField5STOCK_MINIMO_RESPUESTO;
    }

    public JRadioButton getjRadioButton1() {
        return jRadioButton1;
    }

    public JRadioButton getjRadioButton2() {
        return jRadioButton2;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JTextField getjTextField1MONTO_TOTAL_IVA_VENTAS() {
        return jTextField1MONTO_TOTAL_IVA_VENTAS;
    }

    public JTextField getjTextField1precioUnitario_detalleVenta() {
        return jTextField1precioUnitario_detalleVenta;
    }

    public JTextField getjTextField2Cantidad_detalleVenta() {
        return jTextField2Cantidad_detalleVenta;
    }

    public JRadioButton getjRadioButton3() {
        return jRadioButton3;
    }

    public JRadioButton getjRadioButton4() {
        return jRadioButton4;
    }

    public JRadioButton getjRadioButton5() {
        return jRadioButton5;
    }

    public JRadioButton getjRadioButton6() {
        return jRadioButton6;
    }

    public JTextField getjTextField1costoDeEnvio_fabrica() {
        return jTextField1costoDeEnvio_fabrica;
    }

    public JTextField getjTextField2localidad_fabrica() {
        return jTextField2localidad_fabrica;
    }

    public JTextField getjTextField3nombre_fabrica() {
        return jTextField3nombre_fabrica;
    }

    public JComboBox<Object> getjComboBox1Proveedores_respuesto() {
        return jComboBox1Proveedores_respuesto;
    }

    public JComboBox<Object> getjComboBox1repuesto_ventas() {
        return jComboBox1repuesto_ventas;
    }

    public JTextField getjTextField1respuesto_detalleVenta() {
        return jTextField1respuesto_detalleVenta;
    }

    public JTextField getjTextField2ventas_DetalleVenta() {
        return jTextField2ventas_DetalleVenta;
    }

    public JComboBox<Object> getjComboBox1repuesto_fabrica() {
        return jComboBox1repuesto_fabrica;
    }

    public JTextField getjTextField1codigo_repuesto() {
        return jTextField1codigo_repuesto;
    }

    public JComboBox<Object> getjComboBox1repuestos_Repuestos() {
        return jComboBox1repuestos_Repuestos;
    }

    public JTable getjTable1Ventas_Ventas() {
        return jTable1Ventas_Ventas;
    }

    public JTextField getjTextField1_id_cargarStock_repuestos() {
        return jTextField1_id_cargarStock_repuestos;
    }

    public JTextField getjTextField1cargarStockNuevo_repuestos() {
        return jTextField1cargarStockNuevo_repuestos;
    }

    public ButtonGroup getButtonGroup2() {
        return buttonGroup2;
    }

    public ButtonGroup getButtonGroup3() {
        return buttonGroup3;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre_proveedor = new javax.swing.JTextField();
        direccion_proveedor = new javax.swing.JTextField();
        jButton1guardarProveedor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1NOMBRE_RESPUESTO = new javax.swing.JTextField();
        jTextField2CODIGO_RESPUESTO = new javax.swing.JTextField();
        jTextField3STOCK_ACTUAL_RESPUESTO = new javax.swing.JTextField();
        jTextField4PRECIO_RESPUESTO = new javax.swing.JTextField();
        jTextField5STOCK_MINIMO_RESPUESTO = new javax.swing.JTextField();
        jButton1guardar_respuesto = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1Proveedores_respuesto = new javax.swing.JComboBox<>();
        jButton1controlarStockRepuesto = new javax.swing.JButton();
        jTextField1codigo_repuesto = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBox1repuestos_Repuestos = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jTextField1_id_cargarStock_repuestos = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jButton1cargarStock_repuestos = new javax.swing.JButton();
        jTextField1cargarStockNuevo_repuestos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1MONTO_TOTAL_IVA_VENTAS = new javax.swing.JTextField();
        jButton1GUARDAR_VENTAS = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1repuesto_ventas = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Ventas_Ventas = new javax.swing.JTable();
        jButton1CargarTabla_ventas = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1precioUnitario_detalleVenta = new javax.swing.JTextField();
        jTextField2Cantidad_detalleVenta = new javax.swing.JTextField();
        jButton1guardar_detalleVenta = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField1respuesto_detalleVenta = new javax.swing.JTextField();
        jTextField2ventas_DetalleVenta = new javax.swing.JTextField();
        jButton1LimpiarTabla_detalleVenta = new javax.swing.JButton();
        jButton1MostrarComprobante = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1costoDeEnvio_fabrica = new javax.swing.JTextField();
        jTextField2localidad_fabrica = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField3nombre_fabrica = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jButton1guardar_Fabrica = new javax.swing.JButton();
        jComboBox1repuesto_fabrica = new javax.swing.JComboBox<>();
        jButton1LImpiarTablaFabrica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NOMBRE:");

        jLabel2.setText("DIRECCION:");

        jButton1guardarProveedor.setText("Guardar");
        jButton1guardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1guardarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre_proveedor)
                            .addComponent(direccion_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton1guardarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(direccion_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jButton1guardarProveedor)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PROVEEDORES", jPanel1);

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("CODIGO:");

        jLabel5.setText("PRECIO SIN IVA:");

        jLabel6.setText("STOCK ACTUAL:");

        jLabel7.setText("STOCK MINIMO:");

        jButton1guardar_respuesto.setText("Guardar Repuesto");
        jButton1guardar_respuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1guardar_respuestoActionPerformed(evt);
            }
        });

        jLabel17.setText("PROVEEDORES");

        jButton1controlarStockRepuesto.setText("controlar stock ");
        jButton1controlarStockRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1controlarStockRepuestoActionPerformed(evt);
            }
        });

        jLabel22.setText("CODIGO:");

        jLabel23.setText("REPUESTOS CON SU CODIGO:");

        jLabel24.setText("CARGAR STOCK:");

        jLabel26.setText("id:");

        jButton1cargarStock_repuestos.setText("cargar");
        jButton1cargarStock_repuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1cargarStock_repuestosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1repuestos_Repuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1codigo_repuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1controlarStockRepuesto)))
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 120, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox1Proveedores_respuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(248, 248, 248))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1NOMBRE_RESPUESTO, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(jTextField2CODIGO_RESPUESTO, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(jTextField3STOCK_ACTUAL_RESPUESTO, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(jTextField4PRECIO_RESPUESTO, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(jTextField5STOCK_MINIMO_RESPUESTO, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1guardar_respuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1cargarStockNuevo_repuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jTextField1_id_cargarStock_repuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1cargarStock_repuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1NOMBRE_RESPUESTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2CODIGO_RESPUESTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4PRECIO_RESPUESTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1guardar_respuesto)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3STOCK_ACTUAL_RESPUESTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5STOCK_MINIMO_RESPUESTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox1Proveedores_respuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTextField1_id_cargarStock_repuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jTextField1cargarStockNuevo_repuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1cargarStock_repuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1repuestos_Repuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1codigo_repuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jButton1controlarStockRepuesto))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("RESPUESTO", jPanel2);

        jPanel3.setLayout(null);

        jLabel8.setText(" CALCULAR MONTO TOTAL CON IVA:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(160, 90, 211, 14);

        jLabel9.setText("EFECTUO EL PAGO:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(230, 170, 140, 14);
        jPanel3.add(jTextField1MONTO_TOTAL_IVA_VENTAS);
        jTextField1MONTO_TOTAL_IVA_VENTAS.setBounds(450, 80, 245, 30);

        jButton1GUARDAR_VENTAS.setText("Guardar");
        jButton1GUARDAR_VENTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GUARDAR_VENTASActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1GUARDAR_VENTAS);
        jButton1GUARDAR_VENTAS.setBounds(510, 220, 112, 30);

        jLabel18.setText("RESPUESTO:");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(270, 30, 80, 14);

        jPanel3.add(jComboBox1repuesto_ventas);
        jComboBox1repuesto_ventas.setBounds(450, 20, 245, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("SI");
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(440, 170, 35, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("NO");
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(650, 170, 41, 23);

        jLabel25.setForeground(new java.awt.Color(255, 51, 0));
        jLabel25.setText("ingrese el valor sin iva, se calcula automaticamente");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(430, 110, 290, 20);

        jTable1Ventas_Ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id ventas", "Fecha", "Monto total con iva", "Efectuo el pago", "Repuesto"
            }
        ));
        jScrollPane1.setViewportView(jTable1Ventas_Ventas);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(50, 280, 580, 200);

        jButton1CargarTabla_ventas.setText("Cargar Tabla");
        jButton1CargarTabla_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CargarTabla_ventasActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1CargarTabla_ventas);
        jButton1CargarTabla_ventas.setBounds(660, 340, 130, 30);

        jTabbedPane1.addTab("VENTAS", jPanel3);

        jLabel10.setText("PRECIO UNITARIO CON IVA:");

        jLabel11.setText("CANTIDAD:");

        jButton1guardar_detalleVenta.setText("Guardar");
        jButton1guardar_detalleVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1guardar_detalleVentaActionPerformed(evt);
            }
        });

        jLabel19.setText("RESPUESTO:");

        jLabel20.setText("VENTAS:");

        jButton1LimpiarTabla_detalleVenta.setText("Limpiar Tabla");
        jButton1LimpiarTabla_detalleVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LimpiarTabla_detalleVentaActionPerformed(evt);
            }
        });

        jButton1MostrarComprobante.setText("Mostrar Comprobante");
        jButton1MostrarComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1MostrarComprobanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1precioUnitario_detalleVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jTextField2Cantidad_detalleVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jTextField1respuesto_detalleVenta)
                            .addComponent(jTextField2ventas_DetalleVenta)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1LimpiarTabla_detalleVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jButton1guardar_detalleVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1MostrarComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1precioUnitario_detalleVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField2Cantidad_detalleVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField1respuesto_detalleVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField2ventas_DetalleVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton1guardar_detalleVenta)
                .addGap(37, 37, 37)
                .addComponent(jButton1MostrarComprobante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton1LimpiarTabla_detalleVenta)
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("DETALLE VENTA", jPanel4);

        jLabel12.setText("LOCALIDAD:");

        jLabel13.setText("NECESITA ENVIO:");

        jLabel14.setText("NOMBRE:");

        jLabel15.setText("COSTO DE ENVIO:");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("SI");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("NO");

        jLabel16.setText("EFECTUO EL PAGO:");

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setText("SI");

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setText("NO");

        jLabel21.setText("RESPUESTO:");

        jButton1guardar_Fabrica.setText("Guardar");
        jButton1guardar_Fabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1guardar_FabricaActionPerformed(evt);
            }
        });

        jButton1LImpiarTablaFabrica.setText("Limpiar tabla");
        jButton1LImpiarTablaFabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LImpiarTablaFabricaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(44, 44, 44))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(42, 42, 42)))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1costoDeEnvio_fabrica)
                            .addComponent(jTextField2localidad_fabrica, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(jTextField3nombre_fabrica)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jRadioButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton6))
                            .addComponent(jComboBox1repuesto_fabrica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1LImpiarTablaFabrica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1guardar_Fabrica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                .addContainerGap(368, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3nombre_fabrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2localidad_fabrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1costoDeEnvio_fabrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBox1repuesto_fabrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButton1guardar_Fabrica)
                .addGap(18, 18, 18)
                .addComponent(jButton1LImpiarTablaFabrica)
                .addGap(71, 71, 71))
        );

        jTabbedPane1.addTab("FABRICA", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1guardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1guardarProveedorActionPerformed
        this.presentador.guardarProveedorApretado();
    }//GEN-LAST:event_jButton1guardarProveedorActionPerformed

    private void jButton1guardar_respuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1guardar_respuestoActionPerformed
        this.presentador.guardarRespuestoApretado();
    }//GEN-LAST:event_jButton1guardar_respuestoActionPerformed

    private void jButton1GUARDAR_VENTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GUARDAR_VENTASActionPerformed

        this.presentador.guardarVentasApretado();


    }//GEN-LAST:event_jButton1GUARDAR_VENTASActionPerformed

    private void jButton1guardar_detalleVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1guardar_detalleVentaActionPerformed

     
             this.presentador.guardarDetalleVentaApretado();
            
       
      
    }//GEN-LAST:event_jButton1guardar_detalleVentaActionPerformed

    private void jButton1guardar_FabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1guardar_FabricaActionPerformed
        this.presentador.guardarFabricaApretado();
    }//GEN-LAST:event_jButton1guardar_FabricaActionPerformed

    private void jButton1controlarStockRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1controlarStockRepuestoActionPerformed

        this.presentador.controlarStockApretado();
    }//GEN-LAST:event_jButton1controlarStockRepuestoActionPerformed

    private void jButton1CargarTabla_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CargarTabla_ventasActionPerformed
        this.presentador.cargarTablaVentas();
    }//GEN-LAST:event_jButton1CargarTabla_ventasActionPerformed

    private void jButton1cargarStock_repuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1cargarStock_repuestosActionPerformed

        Conexion conexion = new Conexion();
        Connection con = conexion.getConexion();

        int id = Integer.parseInt(jTextField1_id_cargarStock_repuestos.getText());

       // Repuesto id_repuestos = this.presentador.getRepuesto(id);

        //Repuesto repuesto = new Repuesto();

        Repuesto repuesto1 = this.presentador.getRepuesto(id);
        int stock = repuesto1.getStockActual();

        int nuevoStock = Integer.parseInt(jTextField1cargarStockNuevo_repuestos.getText());

        int total = stock + nuevoStock;

        String sql = "UPDATE repuesto SET stockActual='" + total + "'WHERE idrepuesto='" + id + "'";
        try {
            PreparedStatement preparedStatement = con.prepareStatement(sql);
            preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(null, "el stock se cargo correctamente");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1cargarStock_repuestosActionPerformed

    private void jButton1LimpiarTabla_detalleVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LimpiarTabla_detalleVentaActionPerformed
         Conexion conexion = new Conexion();
        Connection con = conexion.getConexion();
        String sql = "delete from detalle_venta";
        try {
            PreparedStatement preparedStatement = con.prepareStatement(sql);
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null, "la lista se limpio correctamente");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1LimpiarTabla_detalleVentaActionPerformed

    private void jButton1MostrarComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1MostrarComprobanteActionPerformed
       this.presentador.mostrarComprobanteApretado();
    }//GEN-LAST:event_jButton1MostrarComprobanteActionPerformed

    private void jButton1LImpiarTablaFabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LImpiarTablaFabricaActionPerformed
        Conexion conexion = new Conexion();
        Connection con = conexion.getConexion();
        
        String sql = "delete from fabricas";
        
        try {
            PreparedStatement preparedStatement = con.prepareStatement(sql);
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null, "la lista se limpio correctamente");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    
    }//GEN-LAST:event_jButton1LImpiarTablaFabricaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField direccion_proveedor;
    private javax.swing.JButton jButton1CargarTabla_ventas;
    private javax.swing.JButton jButton1GUARDAR_VENTAS;
    private javax.swing.JButton jButton1LImpiarTablaFabrica;
    private javax.swing.JButton jButton1LimpiarTabla_detalleVenta;
    private javax.swing.JButton jButton1MostrarComprobante;
    private javax.swing.JButton jButton1cargarStock_repuestos;
    private javax.swing.JButton jButton1controlarStockRepuesto;
    private javax.swing.JButton jButton1guardarProveedor;
    private javax.swing.JButton jButton1guardar_Fabrica;
    private javax.swing.JButton jButton1guardar_detalleVenta;
    private javax.swing.JButton jButton1guardar_respuesto;
    private javax.swing.JComboBox<Object> jComboBox1Proveedores_respuesto;
    private javax.swing.JComboBox<Object> jComboBox1repuesto_fabrica;
    private javax.swing.JComboBox<Object> jComboBox1repuesto_ventas;
    private javax.swing.JComboBox<Object> jComboBox1repuestos_Repuestos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1Ventas_Ventas;
    private javax.swing.JTextField jTextField1MONTO_TOTAL_IVA_VENTAS;
    private javax.swing.JTextField jTextField1NOMBRE_RESPUESTO;
    private javax.swing.JTextField jTextField1_id_cargarStock_repuestos;
    private javax.swing.JTextField jTextField1cargarStockNuevo_repuestos;
    private javax.swing.JTextField jTextField1codigo_repuesto;
    private javax.swing.JTextField jTextField1costoDeEnvio_fabrica;
    private javax.swing.JTextField jTextField1precioUnitario_detalleVenta;
    private javax.swing.JTextField jTextField1respuesto_detalleVenta;
    private javax.swing.JTextField jTextField2CODIGO_RESPUESTO;
    private javax.swing.JTextField jTextField2Cantidad_detalleVenta;
    private javax.swing.JTextField jTextField2localidad_fabrica;
    private javax.swing.JTextField jTextField2ventas_DetalleVenta;
    private javax.swing.JTextField jTextField3STOCK_ACTUAL_RESPUESTO;
    private javax.swing.JTextField jTextField3nombre_fabrica;
    private javax.swing.JTextField jTextField4PRECIO_RESPUESTO;
    private javax.swing.JTextField jTextField5STOCK_MINIMO_RESPUESTO;
    private javax.swing.JTextField nombre_proveedor;
    // End of variables declaration//GEN-END:variables
}
