package modelo;
// Generated 22/02/2020 19:04:04 by Hibernate Tools 4.3.1



/**
 * Transferencia generated by hbm2java
 */
public class Transferencia  implements java.io.Serializable {


     private Integer idtransferencia;
     private Cuentabancaria CuentaDestino;
     private Cuentabancaria CuentaOrigen;
     private double monto;

    public Transferencia() {
    }

    public Transferencia(Cuentabancaria cuentabancariaByCuentaDestino, Cuentabancaria cuentabancariaByCuentaOrigen, double monto) {
       this.CuentaDestino = cuentabancariaByCuentaDestino;
       this.CuentaOrigen = cuentabancariaByCuentaOrigen;
       this.monto = monto;
    }
   
    public Integer getIdtransferencia() {
        return this.idtransferencia;
    }
    
    public void setIdtransferencia(Integer idtransferencia) {
        this.idtransferencia = idtransferencia;
    }
    public Cuentabancaria getCuentabancariaByCuentaDestino() {
        return this.CuentaDestino;
    }
    
    public void setCuentabancariaByCuentaDestino(Cuentabancaria cuentabancariaByCuentaDestino) {
        this.CuentaDestino = cuentabancariaByCuentaDestino;
    }
    public Cuentabancaria getCuentabancariaByCuentaOrigen() {
        return this.CuentaOrigen;
    }
    
    public void setCuentabancariaByCuentaOrigen(Cuentabancaria cuentabancariaByCuentaOrigen) {
        this.CuentaOrigen = cuentabancariaByCuentaOrigen;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    @Override
    public String toString() {
        return "Cuenta Origen= "+ CuentaOrigen.getIdcuentaBancaria() + " Cuenta Destino= " + CuentaDestino.getIdcuentaBancaria() + " Monto= " + monto;
    }
    
    
    




}


