package modelo;
// Generated 25/05/2019 15:45:25 by Hibernate Tools 4.3.1



/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private Integer idcontrato;
     private Cliente cliente;
     private Puesto puesto;
     private int diaInicio;
     private int mesInicio;
     private int añoInicio;
     private int diaFin;
     private int mesFin;
     private int añoFin;
     private String fechaDeCancelacion;
     private double monto;
     private String encargadoDelAlquiler;

    public Contrato() {
    }

	
    public Contrato(Cliente cliente, Puesto puesto, int diaInicio, int mesInicio, int añoInicio, int diaFin, int mesFin, int añoFin, double monto, String encargadoDelAlquiler) {
        this.cliente = cliente;
        this.puesto = puesto;
        this.diaInicio = diaInicio;
        this.mesInicio = mesInicio;
        this.añoInicio = añoInicio;
        this.diaFin = diaFin;
        this.mesFin = mesFin;
        this.añoFin = añoFin;
        this.monto = monto;
        this.encargadoDelAlquiler = encargadoDelAlquiler;
    }
    public Contrato(Cliente cliente, Puesto puesto, int diaInicio, int mesInicio, int añoInicio, int diaFin, int mesFin, int añoFin, String fechaDeCancelacion, double monto, String encargadoDelAlquiler) {
       this.cliente = cliente;
       this.puesto = puesto;
       this.diaInicio = diaInicio;
       this.mesInicio = mesInicio;
       this.añoInicio = añoInicio;
       this.diaFin = diaFin;
       this.mesFin = mesFin;
       this.añoFin = añoFin;
       this.fechaDeCancelacion = fechaDeCancelacion;
       this.monto = monto;
       this.encargadoDelAlquiler = encargadoDelAlquiler;
    }
   
    public Integer getIdcontrato() {
        return this.idcontrato;
    }
    
    public void setIdcontrato(Integer idcontrato) {
        this.idcontrato = idcontrato;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }
    public int getDiaInicio() {
        return this.diaInicio;
    }
    
    public void setDiaInicio(int diaInicio) {
        this.diaInicio = diaInicio;
    }
    public int getMesInicio() {
        return this.mesInicio;
    }
    
    public void setMesInicio(int mesInicio) {
        this.mesInicio = mesInicio;
    }
    public int getAñoInicio() {
        return this.añoInicio;
    }
    
    public void setAñoInicio(int añoInicio) {
        this.añoInicio = añoInicio;
    }
    public int getDiaFin() {
        return this.diaFin;
    }
    
    public void setDiaFin(int diaFin) {
        this.diaFin = diaFin;
    }
    public int getMesFin() {
        return this.mesFin;
    }
    
    public void setMesFin(int mesFin) {
        this.mesFin = mesFin;
    }
    public int getAñoFin() {
        return this.añoFin;
    }
    
    public void setAñoFin(int añoFin) {
        this.añoFin = añoFin;
    }
    public String getFechaDeCancelacion() {
        return this.fechaDeCancelacion;
    }
    
    public void setFechaDeCancelacion(String fechaDeCancelacion) {
        this.fechaDeCancelacion = fechaDeCancelacion;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public String getEncargadoDelAlquiler() {
        return this.encargadoDelAlquiler;
    }
    
    public void setEncargadoDelAlquiler(String encargadoDelAlquiler) {
        this.encargadoDelAlquiler = encargadoDelAlquiler;
    }

    @Override
    public String toString() {
        return  idcontrato + ", cliente=" + cliente.getIdcliente() + ", puesto=" + puesto.getIdpuesto() + ", fechaDeCancelacion=" + fechaDeCancelacion + ", monto=" + monto + ", encargadoDelAlquiler=" + encargadoDelAlquiler + '}';
    }
    
    
    




}


