package modelo;
// Generated 25/05/2019 15:45:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dimension generated by hbm2java
 */
public class Dimension  implements java.io.Serializable {


     private Integer iddimension;
     private String nombre;
     private double ancho;
     private double largo;
     private Set puestos = new HashSet(0);

    public Dimension() {
    }

	
    public Dimension(String nombre, double ancho, double largo) {
        this.nombre = nombre;
        this.ancho = ancho;
        this.largo = largo;
    }
    public Dimension(String nombre, double ancho, double largo, Set puestos) {
       this.nombre = nombre;
       this.ancho = ancho;
       this.largo = largo;
       this.puestos = puestos;
    }
   
    public Integer getIddimension() {
        return this.iddimension;
    }
    
    public void setIddimension(Integer iddimension) {
        this.iddimension = iddimension;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getAncho() {
        return this.ancho;
    }
    
    public void setAncho(double ancho) {
        this.ancho = ancho;
    }
    public double getLargo() {
        return this.largo;
    }
    
    public void setLargo(double largo) {
        this.largo = largo;
    }
    public Set getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Set puestos) {
        this.puestos = puestos;
    }

    @Override
    public String toString() {
        return  iddimension +" " + nombre + " "  + ancho + "x"  + largo ;
    }

   
    
    
    




}


