package modelo;
// Generated 30/12/2019 14:57:30 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fabrica generated by hbm2java
 */
public class Fabrica  implements java.io.Serializable {


     private Integer idfabrica;
     private Repuesto repuesto;
     private Date fecha;
     private String nombre;
     private String direccion;
     private double costoDeEnvio;
     private double precioConIva;
     private int cantidadRepuestos;
     private double total;
     private Set detalleVentas = new HashSet(0);

    public Fabrica() {
    }

	
    public Fabrica(Repuesto repuesto, Date fecha, String nombre, String direccion, double costoDeEnvio, double precioConIva, int cantidadRepuestos, double total) {
        this.repuesto = repuesto;
        this.fecha = fecha;
        this.nombre = nombre;
        this.direccion = direccion;
        this.costoDeEnvio = costoDeEnvio;
        this.precioConIva = precioConIva;
        this.cantidadRepuestos = cantidadRepuestos;
        this.total = total;
    }
    public Fabrica(Repuesto repuesto, Date fecha, String nombre, String direccion, double costoDeEnvio, double precioConIva, int cantidadRepuestos, double total, Set detalleVentas) {
       this.repuesto = repuesto;
       this.fecha = fecha;
       this.nombre = nombre;
       this.direccion = direccion;
       this.costoDeEnvio = costoDeEnvio;
       this.precioConIva = precioConIva;
       this.cantidadRepuestos = cantidadRepuestos;
       this.total = total;
       this.detalleVentas = detalleVentas;
    }
   
    public Integer getIdfabrica() {
        return this.idfabrica;
    }
    
    public void setIdfabrica(Integer idfabrica) {
        this.idfabrica = idfabrica;
    }
    public Repuesto getRepuesto() {
        return this.repuesto;
    }
    
    public void setRepuesto(Repuesto repuesto) {
        this.repuesto = repuesto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public double getCostoDeEnvio() {
        return this.costoDeEnvio;
    }
    
    public void setCostoDeEnvio(double costoDeEnvio) {
        this.costoDeEnvio = costoDeEnvio;
    }
    public double getPrecioConIva() {
        return this.precioConIva;
    }
    
    public void setPrecioConIva(double precioConIva) {
        this.precioConIva = precioConIva;
    }
    public int getCantidadRepuestos() {
        return this.cantidadRepuestos;
    }
    
    public void setCantidadRepuestos(int cantidadRepuestos) {
        this.cantidadRepuestos = cantidadRepuestos;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }

    @Override
    public String toString() {
        return  " id fabrica= " + idfabrica + " nombre= " + nombre + " Direccion "+ direccion + " Repuesto=" + repuesto.getIdrepuesto()   + " precioConIva=" + precioConIva + " cantidad Repuestos=" + cantidadRepuestos + " total=" + total;
    }

   
    
    
    




}


