package modelo;
// Generated 30/12/2019 14:57:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nombrerepuesto generated by hbm2java
 */
public class Nombrerepuesto  implements java.io.Serializable {


     private Integer idnombreRepuesto;
     private String nombre;
     private Set repuestos = new HashSet(0);

    public Nombrerepuesto() {
    }

	
    public Nombrerepuesto(String nombre) {
        this.nombre = nombre;
    }
    public Nombrerepuesto(String nombre, Set repuestos) {
       this.nombre = nombre;
       this.repuestos = repuestos;
    }
   
    public Integer getIdnombreRepuesto() {
        return this.idnombreRepuesto;
    }
    
    public void setIdnombreRepuesto(Integer idnombreRepuesto) {
        this.idnombreRepuesto = idnombreRepuesto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getRepuestos() {
        return this.repuestos;
    }
    
    public void setRepuestos(Set repuestos) {
        this.repuestos = repuestos;
    }

    @Override
    public String toString() {
        return idnombreRepuesto+" "+nombre;
    }
    
    




}


