package modelo;
// Generated 01/03/2019 20:11:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private Proveedor proveedor;
     private double montoTotal;
     private Date fecha;
     private Set compraProductos = new HashSet(0);

    public Compra() {
    }

	
    public Compra(Proveedor proveedor, double montoTotal, Date fecha) {
        this.proveedor = proveedor;
        this.montoTotal = montoTotal;
        this.fecha = fecha;
    }
    public Compra(Proveedor proveedor, double montoTotal, Date fecha, Set compraProductos) {
       this.proveedor = proveedor;
       this.montoTotal = montoTotal;
       this.fecha = fecha;
       this.compraProductos = compraProductos;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public double getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(double montoTotal) {
        this.montoTotal = montoTotal;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getCompraProductos() {
        return this.compraProductos;
    }
    
    public void setCompraProductos(Set compraProductos) {
        this.compraProductos = compraProductos;
    }

    @Override
    public String toString() {
        return  "id:" + idCompra + ", id Proveedor:" + proveedor.getIdproveedor() + ", monto Total:" + montoTotal;
    }
    
    

   

   
    
    




}


