package modelo;
// Generated 01/03/2019 20:11:37 by Hibernate Tools 4.3.1



/**
 * CompraProducto generated by hbm2java
 */
public class CompraProducto  implements java.io.Serializable {


     private Integer id;
     private Compra compra;
     private Producto producto;
     private int cantidad;
     private double precioUnitario;

    public CompraProducto() {
    }

    public CompraProducto(Compra compra, Producto producto, int cantidad, double precioUnitario) {
       this.compra = compra;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }

  
    
    
    




}


