package modelo;
// Generated 01/03/2019 20:11:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idproducto;
     private String nombre;
     private double costo;
     private double ganancia;
     private int stockMinimo;
     private int stockActual;
     private String tipo;
     private Set compraProductos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String nombre, double costo, double ganancia, int stockMinimo, int stockActual, String tipo) {
        this.nombre = nombre;
        this.costo = costo;
        this.ganancia = ganancia;
        this.stockMinimo = stockMinimo;
        this.stockActual = stockActual;
        this.tipo = tipo;
    }
    public Producto(String nombre, double costo, double ganancia, int stockMinimo, int stockActual, String tipo, Set compraProductos) {
       this.nombre = nombre;
       this.costo = costo;
       this.ganancia = ganancia;
       this.stockMinimo = stockMinimo;
       this.stockActual = stockActual;
       this.tipo = tipo;
       this.compraProductos = compraProductos;
    }
   
    public Integer getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getCosto() {
        return this.costo;
    }
    
    public void setCosto(double costo) {
        this.costo = costo;
    }
    public double getGanancia() {
        return this.ganancia;
    }
    
    public void setGanancia(double ganancia) {
        this.ganancia = ganancia;
    }
    public int getStockMinimo() {
        return this.stockMinimo;
    }
    
    public void setStockMinimo(int stockMinimo) {
        this.stockMinimo = stockMinimo;
    }
    public int getStockActual() {
        return this.stockActual;
    }
    
    public void setStockActual(int stockActual) {
        this.stockActual = stockActual;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getCompraProductos() {
        return this.compraProductos;
    }
    
    public void setCompraProductos(Set compraProductos) {
        this.compraProductos = compraProductos;
    }

    @Override
    public String toString() {
        return  "id:" + idproducto + ", nombre:" + nombre + ", costo:" + costo + ", ganancia:" + ganancia + ", stoc kMinimo:" + stockMinimo + ", stock Actual:" + stockActual + ", tipo:" + tipo;
    }
    
    




}


