/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author pablo
 */
public class Contraseña extends javax.swing.JFrame {

    private VistaPrincipal vistaPrincipal;
   

    /**
     * Creates new form Contraseña
     */
    public Contraseña() {
        initComponents();
        setLocationRelativeTo(this);
        this.vistaPrincipal = new VistaPrincipal();

    }

    public JPasswordField getjPassword_CONTRASEÑA() {
        return jPassword_CONTRASEÑA;
    }

    public JTextField getjTextField1_USUARIO() {
        return jTextField1_USUARIO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1_USUARIO = new javax.swing.JTextField();
        jPassword_CONTRASEÑA = new javax.swing.JPasswordField();
        jButton1Salir = new javax.swing.JButton();
        jButton1Entrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(82, 82, 80, 17);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        jTextField1_USUARIO.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1_USUARIO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField1_USUARIO);
        jTextField1_USUARIO.setBounds(180, 75, 197, 28);

        jPassword_CONTRASEÑA.setBackground(new java.awt.Color(204, 204, 204));
        jPassword_CONTRASEÑA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jPassword_CONTRASEÑA);
        jPassword_CONTRASEÑA.setBounds(180, 154, 197, 29);

        jButton1Salir.setBackground(new java.awt.Color(0, 255, 255));
        jButton1Salir.setText("Salir");
        jButton1Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Salir);
        jButton1Salir.setBounds(310, 260, 111, 36);

        jButton1Entrar.setBackground(new java.awt.Color(0, 255, 255));
        jButton1Entrar.setText("Entrar");
        jButton1Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EntrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Entrar);
        jButton1Entrar.setBounds(80, 260, 111, 36);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(53, 53, 53))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 40, 440, 190);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EntrarActionPerformed

        String usuario = "pablo";
        String contraseña = "peruchi";

        if (jTextField1_USUARIO.getText().equals(usuario) && jPassword_CONTRASEÑA.getText().equals(contraseña)) {
            this.vistaPrincipal.setVisible(true);
            this.vistaPrincipal.setLocationRelativeTo(this);
        } else {
            JOptionPane.showMessageDialog(null, "usuario o contraseña incorrecta");
        }
    }//GEN-LAST:event_jButton1EntrarActionPerformed

    private void jButton1SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Entrar;
    private javax.swing.JButton jButton1Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword_CONTRASEÑA;
    private javax.swing.JTextField jTextField1_USUARIO;
    // End of variables declaration//GEN-END:variables
}
