package modelo;
// Generated 03/04/2020 21:15:53 by Hibernate Tools 4.3.1



/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idfactura;
     private String cliente;
     private String plato;
     private String mesa;
     private double cantidad;
     private double total;

    public Factura() {
    }

    public Factura(String cliente, String plato, String mesa, double cantidad, double total) {
       this.cliente = cliente;
       this.plato = plato;
       this.mesa = mesa;
       this.cantidad = cantidad;
       this.total = total;
    }
   
    public Integer getIdfactura() {
        return this.idfactura;
    }
    
    public void setIdfactura(Integer idfactura) {
        this.idfactura = idfactura;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getPlato() {
        return this.plato;
    }
    
    public void setPlato(String plato) {
        this.plato = plato;
    }
    public String getMesa() {
        return this.mesa;
    }
    
    public void setMesa(String mesa) {
        this.mesa = mesa;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }




}


