package modelo;
// Generated 10/04/2020 15:44:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Platosybebidas generated by hbm2java
 */
public class Platosybebidas  implements java.io.Serializable {


     private Integer idplato;
     private String nombre;
     private double costo;
     private double precioAlPublico;
     private String tipo;
     private String ingredientes;
     private Set pedidos = new HashSet(0);

    public Platosybebidas() {
    }

	
    public Platosybebidas(String nombre, double costo, double precioAlPublico, String tipo, String ingredientes) {
        this.nombre = nombre;
        this.costo = costo;
        this.precioAlPublico = precioAlPublico;
        this.tipo = tipo;
        this.ingredientes = ingredientes;
    }
    public Platosybebidas(String nombre, double costo, double precioAlPublico, String tipo, String ingredientes, Set pedidos) {
       this.nombre = nombre;
       this.costo = costo;
       this.precioAlPublico = precioAlPublico;
       this.tipo = tipo;
       this.ingredientes = ingredientes;
       this.pedidos = pedidos;
    }
   
    public Integer getIdplato() {
        return this.idplato;
    }
    
    public void setIdplato(Integer idplato) {
        this.idplato = idplato;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getCosto() {
        return this.costo;
    }
    
    public void setCosto(double costo) {
        this.costo = costo;
    }
    public double getPrecioAlPublico() {
        return this.precioAlPublico;
    }
    
    public void setPrecioAlPublico(double precioAlPublico) {
        this.precioAlPublico = precioAlPublico;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getIngredientes() {
        return this.ingredientes;
    }
    
    public void setIngredientes(String ingredientes) {
        this.ingredientes = ingredientes;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

    @Override
    public String toString() {
        return  idplato + " " + nombre;
    }

  
    
    
    




}


