/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JComboBox;
import javax.swing.JTextField;
import presentador.Presentador;

/**
 *
 * @author pablo
 */
public class ClientesVistas extends javax.swing.JFrame {
    
    private Presentador presentador;

    /**
     * Creates new form ClientesVistas
     */
    public ClientesVistas() {
        initComponents();
        setLocationRelativeTo(this);
        this.presentador = new Presentador(this);
    }

    public JTextField getjTextField1apellidoCliente() {
        return jTextField1apellidoCliente;
    }

    public JTextField getjTextField2nombreCliente() {
        return jTextField2nombreCliente;
    }

    public JTextField getjTextField3direccionCliente() {
        return jTextField3direccionCliente;
    }
    
    
    
    
    

  

    

    
    
    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1apellidoCliente = new javax.swing.JTextField();
        jTextField2nombreCliente = new javax.swing.JTextField();
        jTextField3direccionCliente = new javax.swing.JTextField();
        jButton1guardarCliente = new javax.swing.JButton();
        jButton1salirCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(776, 532));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 50, 61, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 90, 61, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Direccion:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 130, 73, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CLIENTES.1, mas chico.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 30, 130, 120);
        getContentPane().add(jTextField1apellidoCliente);
        jTextField1apellidoCliente.setBounds(190, 80, 180, 30);
        getContentPane().add(jTextField2nombreCliente);
        jTextField2nombreCliente.setBounds(190, 40, 180, 30);
        getContentPane().add(jTextField3direccionCliente);
        jTextField3direccionCliente.setBounds(190, 120, 180, 30);

        jButton1guardarCliente.setBackground(new java.awt.Color(0, 0, 0));
        jButton1guardarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1guardarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButton1guardarCliente.setText("Guardar");
        jButton1guardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1guardarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1guardarCliente);
        jButton1guardarCliente.setBounds(240, 183, 140, 40);

        jButton1salirCliente.setBackground(new java.awt.Color(0, 0, 0));
        jButton1salirCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1salirCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButton1salirCliente.setText("Salir");
        jButton1salirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1salirClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1salirCliente);
        jButton1salirCliente.setBounds(450, 183, 61, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo negro.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -10, 780, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1guardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1guardarClienteActionPerformed
      this.presentador.guardarClienteApretado();
    }//GEN-LAST:event_jButton1guardarClienteActionPerformed

    private void jButton1salirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1salirClienteActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1salirClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesVistas().setVisible(true);
            }
        });
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1guardarCliente;
    private javax.swing.JButton jButton1salirCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1apellidoCliente;
    private javax.swing.JTextField jTextField2nombreCliente;
    private javax.swing.JTextField jTextField3direccionCliente;
    // End of variables declaration//GEN-END:variables
}
