/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JTextArea;
import javax.swing.JTextField;
import presentador.Presentador;

/**
 *
 * @author pablo
 */
public class PlatoVistas extends javax.swing.JFrame {
    
    private Presentador presentador;

    /**
     * Creates new form PlatoVistas
     */
    public PlatoVistas() {
        initComponents();
        setLocationRelativeTo(this);
        this.presentador = new Presentador(this);
    }

    public JTextField getjTextField1precioAlPublico_plato() {
        return jTextField1precioAlPublico_plato;
    }

    public JTextField getjTextField2nombre_plato() {
        return jTextField2nombre_plato;
    }

    public JTextField getjTextField3costoDelPlato_plato() {
        return jTextField3costoDelPlato_plato;
    }

    public JTextArea getjTextArea1ingredientes_plato() {
        return jTextArea1ingredientes_plato;
    }
    
    
    
    

   
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1precioAlPublico_plato = new javax.swing.JTextField();
        jTextField2nombre_plato = new javax.swing.JTextField();
        jTextField3costoDelPlato_plato = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1ingredientes_plato = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton1salirPlato = new javax.swing.JButton();
        jButton1guardarPlato1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(768, 515));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio al Publico:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 120, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingredientes:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 210, 100, 20);
        getContentPane().add(jTextField1precioAlPublico_plato);
        jTextField1precioAlPublico_plato.setBounds(340, 120, 190, 30);
        getContentPane().add(jTextField2nombre_plato);
        jTextField2nombre_plato.setBounds(340, 40, 190, 30);
        getContentPane().add(jTextField3costoDelPlato_plato);
        jTextField3costoDelPlato_plato.setBounds(340, 80, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Costo del Plato:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 90, 120, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 50, 70, 20);

        jTextArea1ingredientes_plato.setColumns(20);
        jTextArea1ingredientes_plato.setRows(5);
        jScrollPane1.setViewportView(jTextArea1ingredientes_plato);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 170, 190, 96);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PLATO.2.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 40, 150, 140);

        jButton1salirPlato.setBackground(new java.awt.Color(0, 0, 0));
        jButton1salirPlato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1salirPlato.setForeground(new java.awt.Color(255, 255, 255));
        jButton1salirPlato.setText("Salir");
        jButton1salirPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1salirPlatoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1salirPlato);
        jButton1salirPlato.setBounds(600, 140, 80, 40);

        jButton1guardarPlato1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1guardarPlato1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1guardarPlato1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1guardarPlato1.setText("Guardar");
        jButton1guardarPlato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1guardarPlato1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1guardarPlato1);
        jButton1guardarPlato1.setBounds(580, 70, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo negro.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1guardarPlato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1guardarPlato1ActionPerformed
        this.presentador.guardarComidasYbebidasApretado();
    }//GEN-LAST:event_jButton1guardarPlato1ActionPerformed

    private void jButton1salirPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1salirPlatoActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1salirPlatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlatoVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlatoVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlatoVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlatoVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlatoVistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1guardarPlato1;
    private javax.swing.JButton jButton1salirPlato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1ingredientes_plato;
    private javax.swing.JTextField jTextField1precioAlPublico_plato;
    private javax.swing.JTextField jTextField2nombre_plato;
    private javax.swing.JTextField jTextField3costoDelPlato_plato;
    // End of variables declaration//GEN-END:variables
}
